name = "Comparator"
version = "0.1.0"
defaultTargets = ["comparator"]

[[lean_lib]]
name = "Comparator"

[[lean_exe]]
name = "comparator"
root = "Main"

[[require]]
name = "lean4export"
path = "../lean4export"
