from pathlib import Path
import yaml
src=Path('/private/tmp/nla-20260922-ie14/linear-systems-and-elimination/IE-14/lean/formalization.yaml')
x=yaml.safe_load(src.read_text())
x['project']['name']='IE-13: sharp complex GEPP growth for arbitrary bandwidths'
x['project']['description']='Full dimension-independent sharp growth for every unequal bandwidth pair, strengthened to all p,q≥0; complex all-tie paths, exact rational attainment and genuine real supremum.'
base='85490781eb0ca01c4545ded776117d7cb4cf9f52'
x['sources']=[{'title':'IE-13 — Sharp growth for unequal lower and upper bandwidths','id':f'https://github.com/sidneyholden1/OpenProblemsInNLA/blob/{base}/linear-systems-and-elimination/IE-13/README.md','type':'web-post','location':'Complete canonical problem statement','relationship':'formalizes','author_endorsement':'not-contacted'},{'title':'Sharp partial-pivoting growth for unequal bandwidths','authors':['Matthew J. Colbrook'],'id':f'https://github.com/sidneyholden1/OpenProblemsInNLA/blob/{base}/references/colbrook-recovered-2026-09-11/manuscripts/IE-13.tex','type':'manuscript','location':'Theorem 1 and complete Sections 2–4','relationship':'formalizes','author_endorsement':'not-contacted','note':'Source attributes mathematics to Matthew J. Colbrook, Cambridge; substantial AI assistance and reconstruction disclosed. Higham retains original-target credit.'}]
x['related_formalizations'][0]={'id':'https://github.com/sidneyholden1/OpenProblemsInNLA/tree/736845bc/linear-systems-and-elimination/IE-15/lean','relationship':'other','note':'Padded active-state and exact Schur layout studied. The separately reviewed IE-14 complex column-only GEPP boundary is adapted locally; no IE-14 proof result or cross-project import is assumed. IE-15 itself is real rook pivoting and its bound is not substituted.'}
x['automation']['methods'][0]['prompting_notes']='Full all-parameter numerical statements first, two independent nonauthor approvals before proof; derive the p-row original-label front and sorted envelope from actual complex GEPP. Exact finite sums and algebra, LeanCert kernel audits; no unnecessary interval calculations.'
x['status']['scope']='Statements only; four deliberate Challenge placeholders. Full original target strengthened to all p,q≥0, including zero bandwidths; no mathematical proof or Solution implementation. Independent statement approvals, full proof, final reviews and Linux Comparator pending; canonical status unchanged.'
x['status']['sorry_count']=4;x['status']['sorry_in_definitions']=0
names=['upper_bound','rational_attainment','sharp_maximum','original_target']
x['status']['main_results']=[{'declaration':'NLA.IE13.'+n,'file':'Challenge.lean','sorry_count':1,'comparator_config':'comparator.json','literature_dependencies':[]} for n in names]
x['fidelity']['divergences']='The complete canonical unequal-bandwidth target is strengthened to all p,q≥0. Arbitrary complex nonsingular matrices, bandwidths at most p,q in the original ordering, all n≥1+max(p,q), all actual GEPP ties and all active entries are retained. The sharp value is 1 if p=0 and h(p,p+q) otherwise, with the exact source zero-extended recurrence. Actual full rational witness paths and genuine nonempty bounded real suprema are conclusions. No front invariant, normalization, pivot admissibility or desired scalar bound is assumed. Optional closed-form specializations are not separate advertised results.'
x['review']={'status':'statement-review-pending','reviewers':['OpenAI Codex agent /root/iv06_statement_referee_2','OpenAI Codex agent /root/new_target_screen'],'notes':'Statement/proof authors /root and /root/iv06_statement_referee_1 do not count as independent referees. Two nonauthor statement approvals and successful Challenge elaboration required before proof; final reviews and actual isolated Linux Comparator remain pending.'}
x['alignment']=[{'source':s,'declarations':['NLA.IE13.'+n]} for s,n in zip(['Universal complex all-dimension all-path upper bound','Actual rational attainment at admissible order','Greatest element of the entire growth set','Complete canonical genuine-supremum classification'],names)]
header='# yaml-language-server: $schema=https://raw.githubusercontent.com/mathlib-initiative/formalization.yaml/99c678e569c7c4c0772db297c5ddd5e4c9b6322e/schema/v0.4.schema.json\n'
Path('formalization.yaml').write_text(header+yaml.safe_dump(x,sort_keys=False,allow_unicode=True,width=100))
