from pathlib import Path
from fractions import Fraction
import json,hashlib,subprocess,re
BASE='deb549fa9ddd6b119e6c59016f268237e645dfa2'
H=lambda b:hashlib.sha256(b).hexdigest()
source_extra={'FR-12':['frames-and-matrix-designs/FR-12/solution.md','frames-and-matrix-designs/FR-12/solution.tex'],'MF-16':['references/colbrook-matrix-functions-2026-09-11/manuscripts/MF-16.tex'],'TR-15':['references/colbrook-unclaimed-2026-09-11/manuscripts/TR-15.md'],'IE-18':['references/colbrook-recovered-2026-09-11/manuscripts/IE-18.tex'],'IE-19':['references/colbrook-recovered-2026-09-11/manuscripts/IE-19.tex']}
notes={
'FR-12':'''The full original target is the existence of a single arbitrary positive real C bounding the count at every positive multiple of four. hadamardCount is Nat.card of exactly the real sign-matrix subtype with the actual Gram identity; labels are never quotiented or normalized. Nat.card would totalize an infinite type to zero, so counting_semantics explicitly requires finiteness in every dimension and the actual Mathlib IsHadamard equivalence at positive dimension. Mathlib's predicate includes unitary entries and both Gram identities. Over the reals the entry condition is precisely ±1, and the reverse Gram identity follows from positive n and the nonsingular one-sided identity. There is no assumed finite family cardinality or existence at unsupported orders.

The actual block/reindex construction keeps the top A,B rows and permutes the lower paired rows by a genuine permutation. Top rows recover A,B; equality of first halves and distinctness of positive-order Hadamard rows recover the permutation. This gives m!, not the source's stronger all-perfect-matching (2m−1)!! factor. That restriction concerns only the injected family, not the objects counted or the universal target. Both canonical and formal metadata explicitly exclude the stronger recurrence. The seven signatures cover semantics, injection, cardinal recurrence, power-of-two nonemptiness, the exact all-k lower bound, strict counterexamples for every positive real C and full universal negation. Natural K=k+2 eliminates truncated subtraction while retaining precisely 2^K(K−1)(K−2)/8. The inner power is natural and the outer power is real; Real.log n / Real.log2 is genuine base-two logarithm. All exhibited dimensions are positive multiples of four.

I independently enumerated the complete labeled order1/2 sign-matrix sets and the restricted map: H(1)=2, H(2)=8, with4/128 distinct outputs from4/128 triples. These are construction output counts, not claims that H(2)=4 or H(4)=128. They are only finite diagnostics; universal injectivity, finiteness, exponential induction and an actual Archimedean choice must be proved later. Exact symbolic cardinality/factorial/log APIs are appropriate; a decorative interval certificate is unnecessary. The full original negative result is covered, not Hadamard existence at every admissible order or a matching upper bound. George Stepaniants is credited for both the mathematical construction and formalization; Ferber–Jain–Zhao keep the conjecture and prior upper-bound credit.''',
'MF-16':'''The full target quantifies every finite ordinary two-letter list equal to its reversal and containing X, every complex Hermitian positive definite B,P of order two, and exactly one complex Hermitian positive definite solution. evalWord is the actual written-order List.prod of matrices. There is no real-only, diagonal, commuting or fixed-word restriction in the conjecture. The witness has16letters,14X and2B. Two distinct genuine complex positive definite solutions for this single admissible word suffice to refute the entire universal assertion; the source's degree theorem, third solution and exponent-family threshold are explicitly excluded.

All nine signatures are meaningful obligations: word semantics; source positive-definite data and exact determinants; actual twelfth-power reduction; bidirectional polynomial/word-entry equivalence; actual Krawczyk acceptance and whole-box bound; unique real root inside the box; recovery of a distinct full complex matrix solution; counterexample; full negation. The original B,P,X0 are unchanged. The independent exact product gives X0 B X0^12 B X0=P, det B=1, det X0=3 and det P=3^14. The trace-polynomial coefficients agree with the determinant-three Cayley–Hamilton recurrence. The polynomial AST has only constants, three in-range variables, add/mul/neg, and imposes xz−y²=3 as an equation, not an assumed parametrization with a potentially invalid denominator.

I inspected the actual LeanCert FinBoxMem, evalFin/SystemZero, intervalJacobian, preconditionedJacobian, infinity row-bound, point image enclosure and krawczykCheck definitions, plus the actual krawczykCheck_sound theorem. The checker requires supported AD, center containment, nonzero actual preconditioner determinant, strict contraction below1 and strict self-map inclusion. Its soundness yields an actual unique real zero in the complete closed box; no approximate root is assumed. The entire specified radius10^-7 box is used. I independently reconstructed the exact rational forward interval AD and obtained contraction0.0264384004893…<27/1000 and inclusion margin9.7317056722…×10^-8>radius/2. A separate Definitions-only Lean #eval returned true and exactly the same rational determinant, radius and contraction. These are diagnostics, not kernel proof certificates; later proof review must inspect the actual Boolean equality proof and its material use.

The matrix-recovery obligations close every escape hatch: x>3 ensures a positive leading minor and separation from X0; determinant3 plus that minor gives genuine complex positive definiteness after the entrywise ofReal map; the ordinary palindrome proves symmetry; determinant multiplicativity gives3^14; the two known entries and P11>0 determine the final diagonal entry. root_to_matrix explicitly requires all matrix entries equal, so the reduced two-entry system is not the final target. Local uniqueness inside the root box is kept distinct from global word uniqueness, which is disproved. Mathlib PosDef means Hermitian and positive quadratic form on every nonzero complex vector. The optimized one-box polynomial route is faithful and avoids the source's much smaller two-dimensional boxes and degree argument. Colbrook's mathematical credit, Stepaniants's formalization credit and original Hillar–Johnson/Armstrong–Hillar attribution are preserved.''',
'TR-15':'''The original universal implication retains all odd m≥3, all q≥2,n≥2 and every finite real common generator. Actual lower order/dimension are m and q(n−1)+1; upper order/dimension are qm and n. generatorIndex is a bounded finite sum of zero-based coordinates; it agrees with the canonical one-based sum minus order. The lower Fin.cast identifies equal lengths and retains the same data, with no out-of-range default or reordered generator. The tensor is the full finite array. contraction sums every ordered (s−1)-tuple, with no factorial normalization, and IsHEigenpair uses nonzero real vectors, every component and ordinary signed-coordinate integer powers. The total order-zero definition is outside all admissible parameters.

Every real lower eigenpair is universally quantified in the strict-positivity export. HasNoNegativeHEigenvalues is the absence of a pair with negative real eigenvalue; it does not assert nonnegative entries or a positive associated Hankel matrix. The exact first contraction is a strictly positive sum of squares for every nonzero real vector, forcing its eigenvalue positive. I independently reconstructed all27lower entry contributions as exact monomial coefficients and both upper components over all32ordered tuples each. The upper vector(0,1) leaves only the all-one tuple, yielding(0,−1)=−1·(0^5,1^5). All original parameters are admissible.

The seven exports include every lower contraction, the actual upper contraction, universal lower positivity, unconditional lower-pair existence, the negative upper pair, the full admissible counterexample and universal negation. Nonvacuity is a separate required conclusion, not an extra conjecture premise: the actual continuous polynomial2t^4+2t^3+3t²−4t−1 has exact values−1 and2 at0and1, hence an interior root supplies the genuine pair(2+2t+2t²,(1,0,t)). All equations are checked, not just a selected component. No eigenvalue enumeration or numerical root isolation is needed. Finite-array/Finset APIs and the ordinary IVT are appropriate; LeanCert's eventual exact−1<0 point certificate must remain in the final negative-pair argument. The full odd-order target is refuted; the even-lower-order theorem and stronger associated-Hankel-PSD conditions are excluded. Source proof and formalization attribution remain Colbrook and Stepaniants respectively.''',
'IE-18':'''The conjecture retains every n≥2, nonzero real symmetric matrix M and the genuine condition1∉spectrum ℝ M. IsHermitian over ℝ is symmetry. Its actual Mathlib eigenvalue list is obtained from an orthonormal eigenbasis and retains multiplicities; the pair maximum ranges over distinct indices, not distinct scalar values. A finite NNReal supremum of squared scalar nnnorms is exactly the nonnegative pairwise real-square maximum. At n≥2 there are actual pairs. Real division's zero denominator convention matches the canonical value0. No stronger positive-definite or diagonal restriction is inserted into the universal assertion.

The residual map explicitly handles0and otherwise uses the actual dot product with(I−M)v divided by the sum of squared coordinates of(I−M)v. Two compositions are four original Anderson steps. Euclidean norm is explicitly sqrt(sum coordinate²), avoiding Pi's supremum norm. Exclusion of eigenvalue1 ensures the nonzero-domain denominator is nonzero in the original setting; the concrete certificate separately forces both actual denominators positive. amplificationSet includes every actual nonzero-vector ratio. IsGreatest means attainment plus an upper bound on the entire set, expressing the original maximum without an empty/unbounded real-supremum default. The counterexample supplies an actual member exceeding that purported greatest value, so attainment subtleties cannot drive the failure.

Independent exact arithmetic recovered both denominators61/50 and1381/93025, coefficients90/61 and3140/1381, vectors(−2,8,15)/61 and(289,−756,1125)/84241, and the squared ratio1920682/21289638243. All six ordered pair values were checked; their maximum is1/121. The pair expression is already squared in the proposed UNSQUARED norm factor: the correct squared comparison is with1/14641, and1920682·14641=28120705162>21289638243. The signature requires the genuine strict unsquared amplification inequality, which must be derived using nonnegative squares and a positive initial norm. No approximate square root is needed.

The three exports cover exact actual recurrence data, all witness admissibility/spectrum/maximum/strict-violation facts, and negation of the full canonical identity. Positivity of M and I−M is an additional conclusion about this witness, not a universal assumption. The source's stronger parameter-family unbounded underestimation, second example and separate asymptotic convergence question are outside scope. Mathlib spectral/finite-max APIs and exact rational algebra are suitable; the eventual LeanCert scalar certificate must be consumed after these bridges. Colbrook and Stepaniants retain mathematical and formalization credit.''',
'IE-19':'''The universal target retains n≥3,m>0,α≥(n−2)m and every real symmetric J with strictly positive entries bounded entrywise by αI+m11ᵀ and weak diagonal dominance. The parameter arithmetic is real, including n−2, and no strict-dominance, invertibility or Loewner-order premise is added. SharpConjecture includes both the full inequality and equality iff J is the comparison matrix. Refuting its inequality at one admissible instance refutes the whole original yes/no statement; the final two negations state exactly that.

rowSumNorm is the actual finite maximum of sums of real scalar nnnorms, coerced from NNReal; scalar norm equals absolute value. For positive n this is the canonical maximum absolute row-sum norm, not Mathlib's default entrywise matrix norm. Matrix inversion is Mathlib's genuine adjugate/determinant inverse and totalizes singular matrices to0. The counterexample explicitly requires IsUnit det for both J and S, eliminating that totalization artifact. There is no assumed candidate inverse in the theorem hypothesis.

I independently checked all nine entry bounds, symmetry and all three weak dominance inequalities for n=3,α=m=1. The rational matrices K,T satisfy both-sided JK=KJ=I and ST=TS=I. Exact determinants are27/4 and4. Every absolute row sum of K is7/9 and every row sum of T is5/4, so their actual finite maxima are those values, with strict gap17/36. The parameter bound and displayed comparison expression at this instance are exact. The three exports require genuine inverses, both unit determinants, the actual norms, the strict violation and the two full universal negations.

The complete source was read, including its sharp infimum1/(α+m), nonattainment and stronger-order exclusions. Those extra analytic results are not claimed by this formalization. Exact finite matrix algebra and one minimal LeanCert scalar inequality are appropriate; no numerical inverse, approximate eigenvalues or intervals are needed for the matrix data. Actual nonsingularity and the all-row maximum remain later proof obligations. Mathematical authorship is Colbrook's; formalization is Stepaniants's; Hillar–Lin–Wibisono's original conjecture credit remains intact.'''
}
libs={
'FR-12':['Mathlib/LinearAlgebra/Matrix/HadamardMatrix.lean','Mathlib/SetTheory/Cardinal/Finite.lean'],
'MF-16':['Mathlib/LinearAlgebra/Matrix/PosDef.lean','LeanCert/Engine/RootFinding/Krawczyk.lean','LeanCert/Engine/Optimization/Gradient.lean'],
'TR-15':['Mathlib/Data/Fintype/BigOperators.lean','Mathlib/Algebra/BigOperators/Fin.lean'],
'IE-18':['Mathlib/Analysis/Matrix/Spectrum.lean','Mathlib/Order/Bounds/Defs.lean','Mathlib/Data/Finset/Lattice/Fold.lean','Mathlib/Analysis/Normed/Group/Real.lean'],
'IE-19':['Mathlib/LinearAlgebra/Matrix/NonsingularInverse.lean','Mathlib/Data/Finset/Lattice/Fold.lean','Mathlib/Analysis/Normed/Group/Real.lean']}
for e in json.load(open('/private/tmp/nla-fourth-five/projects.json')):
 root=Path(e['root']);project=Path(e['project']);p=root/project;a=root/'docs/lean/reverification-2026-09-14'/e['id'];sources=[str(project.parent/'README.md'),str(project/'README.md'),str(project/'NUMERICAL_TARGETS.md'),str(project/'NLA'/e['id'].replace('-','')/'Definitions.lean'),str(project/'Challenge.lean'),str(project/'comparator.json'),str(project/'formalization.yaml'),str(project/'lean-toolchain'),str(project/'lake-manifest.json'),str(project/'lakefile.toml'),'docs/lean/REVIEW.md']+source_extra[e['id']]
 hashes={}
 for f in sources:
  b=subprocess.check_output(['git','-C',str(root),'show',BASE+':'+f]);q=root/f
  if q.exists():assert q.read_bytes()==b,(e['id'],f)
  hashes[f]={'sha256':H(b),'bytes':len(b),'read_method':'local and immutable Git comparison' if q.exists() else 'git show preserved base'}
 cfg=json.loads((p/'comparator.json').read_text());names=re.findall(r'^theorem\s+(\w+)',(p/'Challenge.lean').read_text(),re.M);assert ['NLA.'+e['id'].replace('-','')+'.'+n for n in names]==cfg['theorem_names'];assert not cfg['definition_names'] and set(cfg['permitted_axioms'])=={'propext','Classical.choice','Quot.sound'}
 build=json.loads((a/'challenge-local.json').read_text());log=(a/'challenge-local.log').read_bytes();assert build['exit_code']==0 and H(log)==build['log_sha256'];assert log.decode().count('declaration uses `sorry`')==len(names) and 'Build completed successfully' in log.decode()
 deps={}
 for f in libs[e['id']]:
  q=p/'.lake/packages'/('LeanCert' if f.startswith('LeanCert') else 'mathlib')/f;deps[f]={'sha256':H(q.read_bytes()),'inspection_scope':'actual relevant definitions and stated semantics, not a full dependency-source audit'}
 nums=json.loads((a/'referee-2-numerical-checks.json').read_text());artifacts={'referee-2-numerical-checks.json':H((a/'referee-2-numerical-checks.json').read_bytes())}
 if e['id']=='MF-16':
  d=json.loads((a/'referee-2-checker-diagnostic.json').read_text());dl=(a/'referee-2-checker-diagnostic.log').read_text();assert d['exit_code']==0 and dl.startswith('true\n');rows=dl.splitlines();assert Fraction(rows[1].replace(' ',''))==Fraction(nums['rational_preconditioner_det']);assert Fraction(rows[2].replace(' ',''))==Fraction(nums['radius']);assert Fraction(''.join(rows[3:]).replace(' ',''))==Fraction(nums['whole_box_contraction']);artifacts.update({f:H((a/f).read_bytes()) for f in ['referee-2-checker-diagnostic.lean','referee-2-checker-diagnostic.log','referee-2-checker-diagnostic.json']})
 evidence={'verdict':'PASS','phase':'statement only','reviewer':'/root/iv06_statement_referee_2 (independent AI agent)','preserved_source_base':BASE,'observed_upstream_main_not_source_base':e['upstream_current_main_observed'],'source_hashes':hashes,'inspected_dependency_definitions':deps,'exports':cfg['theorem_names'],'exact_supplementary_checks':nums,'supplementary_evidence_sha256':artifacts,'coordinator_build':build,'coordinator_build_receipt_sha256':H((a/'challenge-local.json').read_bytes()),'no_active_proof_or_solution_inspected':True,'historical_metadata_claims_not_reaudited':True}
 (a/'referee-2-statement-checks.json').write_text(json.dumps(evidence,indent=2)+'\n')
 provenance='FR-12 has no canonical page at the observed older main, so no cross-revision target identity is claimed.' if e['id']=='FR-12' else 'This approval is bound to the complete canonical target at the preserved snapshot; it does not assert byte equality with the older main or adopt its formatting.'
 text=f'''# {e['id']} — independent statement referee 2

**PASS — approved statement boundary.** No blocking fidelity, vacuity or numerical-data finding. Proof and actual Linux verification remain separate future gates for this campaign.

Reviewer: `/root/iv06_statement_referee_2`, independent AI agent, 2026-09-14. I applied `docs/lean/REVIEW.md`, the local Tau Ceti adaptation, covering complete target fidelity, mathematical meaning, degeneracies, numerical scope, computation reduction, reuse and attribution. This is not official Tau Ceti endorsement or human peer review. I read the full retained canonical page, complete informal source(s), exact numerical plan, actual Definitions and Challenge, comparator configuration, project guide and formalization metadata. I did not inspect active Proof/Solution bodies. Definitions' finite-index/well-formedness proofs are part of the reviewed boundary.

The source is the existing authored snapshot `{BASE}`, preserved from earlier branch ancestry. The observed upstream main is the older `{e['upstream_current_main_observed']}`; this review does not call the source current main or newly authored. {provenance} Existing historical statement-stage notices and old published verification claims remain historical; they do not establish this campaign's proof or Linux gate. Project metadata was checked for target scope and attribution, not as evidence that a new proof run passed.

## Full target and certificate fidelity

{notes[e['id']]}

## Independent checks and remaining obligations

The independent rational/integer reconstruction is in `referee-2-numerical-checks.json`. Its generator `/private/tmp/nla-fourth-five/referee2_numerics.py` was written by this reviewer from the displayed definitions, rather than relying on a saved PASS. These diagnostics check data and feasibility only; they are not proofs of the universal statements. MF-16's #eval, where applicable, imports Definitions only and is explicitly a diagnostic. The actual numerical statements and all necessary bridges are satisfactory before proof inspection.

The coordinator's fresh pinned macOS `lake build Challenge` passed with exactly {len(names)} deliberate placeholder warnings, and I checked its exit-0 receipt and matching log SHA-256. That build is honestly attributed to the coordinator, not this reviewer; placeholders prove no mathematics. All {len(names)} declarations match the exact comparator inventory and there are no definition-name exceptions. Permitted final axioms are only the standard three. The historical manifest's zero proof-hole count excludes its separate Challenge placeholders and is not independently verified at this phase.

The imported semantics inspected are hash-bound below and in the JSON. Familiar Mathlib finite sums, matrix products, real norms, spectrum/positive-definite or finite-count APIs are used with concrete mathematical definitions. Existing reviewed projects from the preceding campaign provide workflow and exact-matrix/counting examples; none of their results is added as an assumption here. Later independent proof review must check the full active dependency closure, material use of LeanCert and all export axioms; actual isolated Linux Comparator must check statement identity and kernel/sandbox rejection controls. No source, metadata or permanent problem ID was changed by this referee.

## Exact reviewed sources

| Source | SHA-256 |
| --- | --- |
'''+''.join(f"| `{f}` | `{h['sha256']}` |\n" for f,h in hashes.items())+'''
## Relevant imported semantics

| Dependency file | SHA-256 |
| --- | --- |
'''+''.join(f"| `{f}` | `{h['sha256']}` |\n" for f,h in deps.items())+f"\nMachine report SHA-256: `{H((a/'referee-2-statement-checks.json').read_bytes())}`. Its source/diagnostic/build hashes bind this approval to the exact bytes reviewed.\n"
 (a/'STATEMENT-REFEREE-2.md').write_text(text);print(e['id'],'PASS',len(names),'exports',flush=True)
