import Mathlib.LinearAlgebra.Matrix.PosDef
import Mathlib.LinearAlgebra.Matrix.Rank
import Mathlib.LinearAlgebra.Matrix.Notation
import Mathlib.Analysis.Matrix.Normed
import Mathlib.Topology.Connected.Basic
import Mathlib.Topology.Constructions

/-!
PF-02 statement draft. Mathematical counterexample: Matthew J. Colbrook,
University of Cambridge, PF-02_disconnected_orbits.tex, Theorem 1.
Prepared by Codex for two independent statement reviews before any proof.

Factorizations retain all real PSD row and column factors, with the inherited
finite-product Euclidean topology. The quotient uses actual invertible real
congruences and Mathlib's coinduced quotient topology. No orientation condition
is imposed on admissible factorizations or allowed changes of basis.
-/
set_option autoImplicit false
noncomputable section
open scoped BigOperators Classical
namespace NLA.PF02

abbrev Mat (k : ℕ) := Matrix (Fin k) (Fin k) ℝ
abbrev Rect (p q : ℕ) := Matrix (Fin p) (Fin q) ℝ
abbrev FactorTuple (p q k : ℕ) := (Fin p → Mat k) × (Fin q → Mat k)

def EntrywiseNonnegative {p q : ℕ} (M : Rect p q) : Prop :=
  ∀ i j, 0 ≤ M i j

def IsPSDFactorization {p q k : ℕ} (M : Rect p q) (F : FactorTuple p q k) : Prop :=
  (∀ i, (F.1 i).PosSemidef) ∧ (∀ j, (F.2 j).PosSemidef) ∧
    ∀ i j, (F.1 i * F.2 j).trace = M i j

abbrev Factorization {p q : ℕ} (M : Rect p q) (k : ℕ) :=
  {F : FactorTuple p q k // IsPSDFactorization M F}

def feasibleSizes {p q : ℕ} (M : Rect p q) : Set ℕ :=
  {k | 1 ≤ k ∧ Nonempty (Factorization M k)}

/-- True minimum over all positive sizes admitting real PSD factors. -/
def psdRank {p q : ℕ} (M : Rect p q) : ℕ := sInf (feasibleSizes M)

/-- Both factor families transform; column factors use the inverse-transpose. -/
def Congruent {p q k : ℕ} {M : Rect p q}
    (F G : Factorization M k) : Prop :=
  ∃ S : (Mat k)ˣ,
    (∀ i, G.val.1 i = S.val.transpose * F.val.1 i * S.val) ∧
    (∀ j, G.val.2 j = (↑(S⁻¹) : Mat k) * F.val.2 j *
      (↑(S⁻¹) : Mat k).transpose)

/-- Quot identifies the relation generated by exactly the displayed congruences.
The Challenge requires equivalence and equality iff an actual congruence. -/
abbrev OrbitSpace {p q : ℕ} (M : Rect p q) (k : ℕ) :=
  Quot (@Congruent p q k M)

def orbitClass {p q k : ℕ} {M : Rect p q} (F : Factorization M k) : OrbitSpace M k :=
  Quot.mk _ F

/-- Full original assertion, retaining ordinary rank and minimal PSD rank. -/
def ConnectedOrbitConjecture : Prop :=
  ∀ (k p q : ℕ), 3 ≤ k → 1 ≤ p → 1 ≤ q →
    ∀ M : Rect p q, EntrywiseNonnegative M →
      M.rank = k * (k + 1) / 2 → psdRank M = k →
        IsConnected (Set.univ : Set (OrbitSpace M k))

def witnessM : Rect 6 6 :=
  !![24,20,20,16,16,16;
     20,24,20,16,16,16;
     20,20,24,16,16,16;
     16,16,16,14,12,12;
     16,16,16,12,14,12;
     16,16,16,12,12,14]

def witnessFactors : Fin 6 → Mat 3 :=
  ![!![4,0,0; 0,2,0; 0,0,2],
    !![2,0,0; 0,4,0; 0,0,2],
    !![2,0,0; 0,2,0; 0,0,4],
    !![2,1,0; 1,2,0; 0,0,2],
    !![2,0,1; 0,2,0; 1,0,2],
    !![2,0,0; 0,2,1; 0,1,2]]

def reflectedFactors : Fin 6 → Mat 3 :=
  fun i => if i = 3 then !![2,-1,0; -1,2,0; 0,0,2] else witnessFactors i

def witnessTuple : FactorTuple 6 6 3 := (witnessFactors, witnessFactors)
def reflectedTuple : FactorTuple 6 6 3 := (reflectedFactors, reflectedFactors)

/-- Coordinates include each symmetric off-diagonal entry exactly once. -/
def symCoordinates (X : Mat 3) : Fin 6 → ℝ :=
  ![X 0 0, X 1 1, X 2 2, X 0 1, X 0 2, X 1 2]

def symOfCoordinates (x : Fin 6 → ℝ) : Mat 3 :=
  !![x 0,x 3,x 4; x 3,x 1,x 5; x 4,x 5,x 2]

def symBasis (i : Fin 6) : Mat 3 := symOfCoordinates (Pi.single i 1)

def rowCoordinates (A : Fin 6 → Mat 3) : Mat 6 := fun i => symCoordinates (A i)

def traceMetric : Mat 6 := Matrix.diagonal (![1,1,1,2,2,2] : Fin 6 → ℝ)

/-- Row convention: coord(SᵀXS) = coord(X) * congruenceCoordinates S. -/
def congruenceCoordinates (S : Mat 3) : Mat 6 :=
  fun i => symCoordinates (S.transpose * symBasis i * S)

def rowOrientation (A : Fin 6 → Mat 3) : ℝ :=
  if 0 < (rowCoordinates A).det then 1 else -1

end NLA.PF02
