import NLA.KE04.Definitions
import LeanCert.Tactic.Verification

set_option leancert.trust "kernel"
#assert_trust kernel NLA.KE04.Vec
#print axioms NLA.KE04.Vec
#assert_trust kernel NLA.KE04.Rect
#print axioms NLA.KE04.Rect
#assert_trust kernel NLA.KE04.Mat
#print axioms NLA.KE04.Mat
#assert_trust kernel NLA.KE04.column
#print axioms NLA.KE04.column
#assert_trust kernel NLA.KE04.act
#print axioms NLA.KE04.act
#assert_trust kernel NLA.KE04.columnSpace
#print axioms NLA.KE04.columnSpace
#assert_trust kernel NLA.KE04.FullColumnRank
#print axioms NLA.KE04.FullColumnRank
#assert_trust kernel NLA.KE04.krylovColumns
#print axioms NLA.KE04.krylovColumns
#assert_trust kernel NLA.KE04.krylov
#print axioms NLA.KE04.krylov
#assert_trust kernel NLA.KE04.krylovCombination
#print axioms NLA.KE04.krylovCombination
#assert_trust kernel NLA.KE04.FullBlockDimension
#print axioms NLA.KE04.FullBlockDimension
#assert_trust kernel NLA.KE04.LastFullBlockIteration
#print axioms NLA.KE04.LastFullBlockIteration
#assert_trust kernel NLA.KE04.IsKrylovBasis
#print axioms NLA.KE04.IsKrylovBasis
#assert_trust kernel NLA.KE04.frameProjection
#print axioms NLA.KE04.frameProjection
#assert_trust kernel NLA.KE04.compression
#print axioms NLA.KE04.compression
#assert_trust kernel NLA.KE04.orderedEigenvalues
#print axioms NLA.KE04.orderedEigenvalues
#assert_trust kernel NLA.KE04.orderedEigenbasis
#print axioms NLA.KE04.orderedEigenbasis
#assert_trust kernel NLA.KE04.eigenvalueAt
#print axioms NLA.KE04.eigenvalueAt
#assert_trust kernel NLA.KE04.ritzValues
#print axioms NLA.KE04.ritzValues
#assert_trust kernel NLA.KE04.ritzValueAt
#print axioms NLA.KE04.ritzValueAt
#assert_trust kernel NLA.KE04.monicQuadratic
#print axioms NLA.KE04.monicQuadratic
#assert_trust kernel NLA.KE04.quadraticMatrix
#print axioms NLA.KE04.quadraticMatrix
#assert_trust kernel NLA.KE04.compressedQuadratic
#print axioms NLA.KE04.compressedQuadratic
#assert_trust kernel NLA.KE04.form
#print axioms NLA.KE04.form
#assert_trust kernel NLA.KE04.IterationOccupancy
#print axioms NLA.KE04.IterationOccupancy
#assert_trust kernel NLA.KE04.FullPrefixBlockLanczosClaim
#print axioms NLA.KE04.FullPrefixBlockLanczosClaim
#assert_trust kernel NLA.KE04.BlockLanczosConjecture
#print axioms NLA.KE04.BlockLanczosConjecture
