from pathlib import Path
from datetime import datetime,timezone
import hashlib,json,re,subprocess,collections,yaml
R=Path('/tmp/nla-lean-mf16-worktree');E=R/'matrix-functions-and-stability/MF-16';P=E/'lean';O=P/'verification/publication-2026-09-12'
C='4e24448897a088ca9e7458379add1014c5d11e0c';BASE='5830ed4fb06da0659414a3deb2a40ad327aca052'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
git=lambda *a:subprocess.check_output(['git',*a],cwd=R)
assert git('rev-parse','HEAD').decode().strip()==C and not git('diff','--name-only','HEAD')
assert not O.exists()
assert sha(P/'verification/root-operational-2026-09-12/ROOT-CHECKS.json')=='a09d923c1406601f672aeb6ae5e64eeac1a639a64e77b06489741a3c3523d684'
assert sha(P/'verification/root-operational-2026-09-12/EVIDENCE-MANIFEST.json')=='b7128ce7792a4eb43e61878e855b39e0d23878a2daa2938da9e0ee9e021512ef'
inputs={}
for path in git('ls-tree','-r','--name-only',C,'--',P.relative_to(R).as_posix()).decode().splitlines():
 rel=str(Path(path).relative_to(P.relative_to(R)));h=hashlib.sha256(git('show',C+':'+path)).hexdigest();assert sha(P/rel)==h;inputs[rel]=h
assert len(inputs)==294
immutable={}
for name,num,h in [('linux-2026-09-12',466,'b8661c4f497acc280bfccdd78e99d06049dc6fc854f09c227b67e65f39eb350a'),('root-operational-2026-09-12',6,'b7128ce7792a4eb43e61878e855b39e0d23878a2daa2938da9e0ee9e021512ef')]:
 root=P/'verification'/name;out=root/'EVIDENCE-MANIFEST.json';assert sha(out)==h;d=json.loads(out.read_text());assert len(d['files'])==num
 actual={str(f.relative_to(root)) for f in root.rglob('*') if f.is_file() and f!=out};assert actual==set(d['files'])
 for rel,v in d['files'].items():
  f=root/rel;assert not f.is_symlink() and f.resolve().is_relative_to(root.resolve());assert sha(f)==v['sha256'] and f.stat().st_size==v['bytes']
 immutable.update({str(f.relative_to(P)):sha(f) for f in root.rglob('*') if f.is_file()})
assert len(immutable)==474
registry=json.loads((R/'problem_ids.json').read_text());counts=collections.Counter(re.search(r'^\*\*Status:\*\*\s+([^\n]+)',(R/path).read_text(),re.M).group(1).strip() for path in registry.values())
assert counts=={'Lean verified':16,'Solved':76,'Open':53,'Partially resolved':72}
canonical=(E/'README.md').read_text();target=canonical[canonical.index('## Problem statement'):]
O.mkdir();(O/'archive').mkdir()
for n,dest in [('README.md','README.linux-candidate.md'),('formalization.yaml','formalization.linux-candidate.yaml')]: (O/'archive'/dest).write_bytes((P/n).read_bytes())
before=dict(utc=datetime.now(timezone.utc).isoformat(),candidate=C,base=BASE,project_inputs=inputs,immutable_operational_files=immutable,canonical_target_sha256=hashlib.sha256(target.encode()).hexdigest(),registry_sha256=sha(R/'problem_ids.json'),status_counts_before=dict(counts),publication_preparer='/root: disclosed proof-route contributor; no independent mathematical review claimed',expected_changed_candidate_inputs=['README.md','formalization.yaml'])
(O/'before.json').write_text(json.dumps(before,indent=2)+'\n')
canonical=canonical.replace('**Last checked:** 2026-09-11','**Last checked:** 2026-09-12',1).replace('**Status:** Solved','**Status:** Lean verified',1)
old='Verification is independent agent review, not external human peer review or formal certification.'
assert old in canonical
canonical=canonical.replace(old,'That dated manuscript review was independent agent review; the separate Lean verification below certifies the full original target. External human peer review is not claimed.',1)
section=r'''## Lean proof and verification evidence — 2026-09-12

**Formalization:** George Stepaniants, Department of Computing and Mathematical Sciences, California Institute of Technology, Pasadena, California, USA, with AI-agent assistance. **Matthew J. Colbrook retains authorship of the mathematical counterexample.**

The [nine formal exports](lean/Solution.lean) refute the complete original universal uniqueness assertion: all finite ordinary two-letter palindromes containing $`X`$, and all complex Hermitian positive definite $`B,P`$ of order two. For the unchanged source word $`XBX^{12}BX`$ and integer matrices, the proof constructs two distinct genuine positive definite solutions. Actual written-order matrix products, complexification and every matrix-entry equality are proved. The original target and mathematical source are retained unchanged.

A single rational box of radius $`10^{-7}`$ is certified by the actual LeanCert Krawczyk checker in explicit kernel mode. Cayley–Hamilton reduces the twelfth power before interval evaluation; determinant and symmetry recover the full word equation. The soundness theorem yields an actual root, and an LDL congruence proves positive definiteness. No numerical root approximation is assumed. The source's stronger three-solution count and exponent-family threshold are outside these nine exports.

Two independent statement approvals preceded proof work, and [two independent final mathematical reports](lean/README.md#review-and-checks-actually-performed) approved the frozen proof. The [actual Ubuntu run](https://github.com/sgstepaniants/OpenProblemsInNLA/actions/runs/34735259429), at immutable revision [4e244488](https://github.com/sgstepaniants/OpenProblemsInNLA/tree/4e24448897a088ca9e7458379add1014c5d11e0c/matrix-functions-and-stability/MF-16/lean), passed all 17 jobs. All nine exports matched without definition exceptions; default-kernel replay, 22 standard-three axiom reports and both real control suites passed as a non-root user. The [independent operational audit](lean/verification/linux-2026-09-12/OPERATIONAL-REVIEW.md) and [coordinator acceptance](lean/verification/root-operational-2026-09-12/ROOT-CHECKS.json) bind all 294 submitted inputs and the original logs/artifacts. Local Mac checks are separately identified. The [v0.4 manifest](lean/formalization.yaml), [numerical targets](lean/NUMERICAL_TARGETS.md) and [proof map](lean/verification/PROOF_MAP.md) document the exact scope.

'''
assert canonical.count('## Problem statement')==1
canonical=canonical.replace('## Problem statement',section+'## Problem statement',1)
assert canonical[canonical.index('## Problem statement'):]==target
(E/'README.md').write_text(canonical)
readme=(P/'README.md').read_text()
old='**The complete nine-export proof has two accepted independent final mathematical approvals. Actual Linux verification is pending.** The [canonical problem](../README.md) remains **Solved**. This candidate documentation does not promote its verification status.'
assert old in readme
readme=readme.replace(old,'**The complete nine-export proof passed independent mathematical review and actual Ubuntu Comparator/default-kernel verification.** The [canonical problem](../README.md) records the full target as **Lean verified**. The immutable checked revision and retained evidence are documented below.',1)
readme=readme.replace('## Reproduction and remaining gates','## Reproduction',1)
old='The unchanged default Lake target is `Challenge`; plain `lake build` therefore checks the reference statements. Its placeholders are not proofs. The isolated Linux workflow must additionally run the pinned Comparator, actual default-kernel replay and both real rejection/control suites. Successful local elaboration alone does not satisfy that gate.'
new='The unchanged default Lake target is `Challenge`; plain `lake build` therefore checks the reference statements. Its placeholders are not proofs. Reproduce the authoritative check from the immutable revision using the repository\'s [Linux verification workflow](../../../.github/workflows/lean-verify.yml) and [pinned checker instructions](../../../docs/lean/README.md). It runs Comparator, actual default-kernel replay and both real rejection/control suites on non-root Ubuntu.'
assert old in readme;readme=readme.replace(old,new,1)
old='Actual Ubuntu verification, independent operational acceptance and publication review remain required before changing the canonical entry to **Lean verified**. The [v0.4 metadata](formalization.yaml) describes the current completed implementation and pending verification scope truthfully. The campaign\'s pinned Schiffer and Forsythe examples and adapted Tau Ceti review protocol are credited in the source correspondence and metadata.'
assert old in readme
readme=readme.replace(old,'''## Actual Ubuntu verification and publication preservation

[Run 34735259429](https://github.com/sgstepaniants/OpenProblemsInNLA/actions/runs/34735259429) checked immutable candidate `4e24448897a088ca9e7458379add1014c5d11e0c`. All 17 jobs and every step passed. The actual checker ran on Ubuntu 24.04 x86_64 with UID 1001, Lean 4.33.1, the pinned Comparator/exporter and strict sandbox. It freshly cloned ten exact dependencies and used 8,690 matching official Mathlib cache files. Challenge and Solution build graphs had 2,840 and 2,863 jobs; these are not counts of a full dependency-source rebuild.

Both actual export lists contain exactly the nine advertised declarations, with no definition exceptions. Default-kernel replay accepted the Solution. All 22 actual source axiom reports match their explicit kernel assertions and contain only `propext`, `Classical.choice`, `Quot.sound`. The final referees' count of 26 additionally includes four computational helper checks; their original evidence is retained. The Solution phase has no warnings or admissions.

The target and standalone checker jobs each executed the actual sandbox probes, three raw-kernel controls, five Comparator fixtures and admission/native rejection controls. The deliberately admitted proof was rejected for `sorryAx`, and native computation for `checked._native.native_decide.ax_1_1`. Nested Bubblewrap was denied UID-map setup before its inner write; the logs do not establish an executed inner-write denial or general sandbox security.

The [independent operational review](verification/linux-2026-09-12/OPERATIONAL-REVIEW.md) and [complete outer inventory](verification/linux-2026-09-12/EVIDENCE-MANIFEST.json) bind 466 evidence files plus the inventory, including all seven nested candidate manifests. The retained 294-input source snapshot agrees with the actual verifier receipt and committed Git blobs. Original project artifact ZIP SHA256 is `0dad309f58da9d61b1b177a550f60d8053938409bc30fe9d57399b719aec1d34`; checker ZIP SHA256 is `62d95b1cd2d2d34e82f0fc95c38cb1a2c2f9257caa7c9af5b50ca95eccf44f66`. Both match GitHub metadata and actual upload logs. The complete 217-log run ZIP is retained with a separately computed digest, without claiming a GitHub-published checksum for that log archive.

Operational reviewer `/root/mf16_final_referee` also served as independent final mathematical referee 1 and independent candidate packaging reviewer. These roles add no mathematical approval. `/root` independently accepted that operational evidence and prepared these publication wrappers, but is a disclosed proof-route contributor and does not count as an independent final mathematical referee. Referee 2 remains `/root/formal_review_standards`. The [root acceptance](verification/root-operational-2026-09-12/ROOT-CHECKS.json) and its complete inventory bind six files plus that outer manifest.

The actual run checks the immutable candidate, not these later publication wrappers. Among its 294 inputs, publication changes only this README and five status/review fields in the [v0.4 manifest](formalization.yaml); the other 292 inputs remain unchanged. Both exact candidate wrappers are archived under [publication evidence](verification/publication-2026-09-12/archive/). All 467 Linux evidence files, seven root operational files, 182 frozen proof inputs through the historical README archive, 45 statement inputs and fourteen original source snapshots remain intact. The canonical original mathematical target and source manuscripts are unchanged. Earlier pending notices remain historical phase records.

The campaign's pinned Schiffer and Forsythe examples and adapted Tau Ceti protocol are credited in the source correspondence and metadata. Separate publication review is required before commit, fork push and individual upstream PR. No new proof run over these wrappers, external human review, official Tau Ceti endorsement or mathematical priority is claimed.''',1)
(P/'README.md').write_text(readme)
path=P/'formalization.yaml';header=path.read_text().splitlines()[0];d=yaml.safe_load(path.read_text())
d['status']['scope']='Complete nine-export negative answer to the full original all-ordinary-palindromes, all-complex-Hermitian-positive-definite order-two uniqueness conjecture. Two independent statement approvals preceded proof work; two independent final mathematical approvals and actual Ubuntu Comparator/default-kernel run 34735259429 at '+C+' passed. Independent operational review and root acceptance bind all 294 submitted inputs and both real control suites. Canonical status is Lean verified. The stronger three-root and exponent-family assertions are outside these exports.'
d['review']['status']='agent-reviewed; Linux-Comparator-and-default-kernel-verified'
d['review']['notes']='Both independent statement approvals preceded implementation. Both independent final referees freshly elaborated and inspected the complete original target and material Krawczyk/Cayley-Hamilton/complex-PD/all-entry matrix-word proof; each recorded ten successful checks and 26 standard-three reports including four extra computational helpers. Local checks used read-only clean pinned MI22 dependencies, no old target objects, and are identified as macOS. Actual Ubuntu run 34735259429 at '+C+' passed all 17 jobs and steps, matched all nine exports without definition exceptions, accepted the default kernel, and recorded 22 embedded source kernel/standard-three reports. Both real sandbox/kernel/Comparator/admission/native control suites passed under UID 1001. Ten dependencies were freshly cloned and 8690 matching official Mathlib cache files used, not a full dependency-source rebuild. Nested Bubblewrap was denied UID-map setup before any inner write. Operational reviewer /root/mf16_final_referee also served as independent final referee 1 and candidate packager; referee 2 is /root/formal_review_standards. Root is a proof-route contributor, separately accepted operational evidence and prepared publication wrappers, not an independent final mathematical referee. Operational report SHA256 e348886719fab4d2dca6aeba02d711d938f22b97c9529c6e91a2e70f086bf960 and outer b8661c4f497acc280bfccdd78e99d06049dc6fc854f09c227b67e65f39eb350a bind 466 files plus itself including seven nested manifests; root checks SHA256 a09d923c1406601f672aeb6ae5e64eeac1a639a64e77b06489741a3c3523d684 confirm acceptance. Both exact candidate wrappers are archived; only README and five status/review fields change among 294 candidate inputs, preserving 292 others, 467 Linux files, seven root operational files, all frozen mathematical inputs and fourteen source snapshots. Separate publication review remains required. No local check is reported as authoritative Linux, and no external human review, official Tau Ceti endorsement or new mathematical priority is claimed.'
d['review']['linux_verification']['status']='passed; independently audited and root accepted'
d['review']['linux_verification']['note']='Actual run https://github.com/sgstepaniants/OpenProblemsInNLA/actions/runs/34735259429 at '+C+'. All nine exports, default-kernel replay, 22 standard-three reports and both actual control suites pass. Complete original artifact ZIPs, all 217 run logs and exact 294-input snapshot are retained under verification/linux-2026-09-12, with independent OPERATIONAL-REVIEW.md and complete EVIDENCE-MANIFEST.json. See verification/root-operational-2026-09-12/ROOT-CHECKS.json for coordinator acceptance. Linux verifies the immutable candidate; publication archives its exact wrappers and preserves all other inputs.'
path.write_text(header+'\n'+yaml.safe_dump(d,sort_keys=False,allow_unicode=True,width=100))
s=(R/'RESOLVED.md').read_text();marker='**MF-16 (Solved).**';a=s.index(marker);b=s.index('\n\n',a);block=s[a:b];block=block.replace(marker,'**MF-16 (Lean verified; formalization by George Stepaniants).**',1)
block+=r''' **Lean verification — 2026-09-12:** George Stepaniants, Department of Computing and Mathematical Sciences, California Institute of Technology, Pasadena, California, USA, with AI-agent assistance. Matthew J. Colbrook retains mathematical authorship. The [nine exports](matrix-functions-and-stability/MF-16/lean/Solution.lean) negate the full original universal complex positive-definite uniqueness target using two distinct solutions of the unchanged word equation. The source's stronger three-solution count and exponent-family threshold are outside those exports. A genuine LeanCert Krawczyk root certificate in explicit kernel mode, actual Cayley–Hamilton reduction and full complex matrix-word recovery establish the result. Two independent statement and two independent final mathematical reviews were followed by [actual Ubuntu run 34735259429](https://github.com/sgstepaniants/OpenProblemsInNLA/actions/runs/34735259429), with all nine exports, default-kernel replay, 22 standard-three reports and both real control suites passing. The [canonical evidence](matrix-functions-and-stability/MF-16/README.md#lean-proof-and-verification-evidence---2026-09-12) links the complete operational audit and root acceptance binding all 294 candidate inputs. External human peer review is not claimed.'''
(R/'RESOLVED.md').write_text(s[:a]+block+s[b:])
(O/'prepare.py').write_bytes(Path(__file__).read_bytes())
print(json.dumps({'prepared':'MF-16','candidate_inputs':len(inputs),'immutable_evidence_files':len(immutable),'target_unchanged':True},indent=2))
