name = "NLAIS03"
version = "0.1.0"
defaultTargets = ["Challenge"]

[[require]]
name = "leancert"
git = "https://github.com/alerad/leancert"
rev = "621a43d7cf21f87872392a01e874f2f1dbddc926"

[[lean_lib]]
name = "NLA"

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "Solution"
