from pathlib import Path
import yaml
old=Path('/private/tmp/nla-20260922-mf12/matrix-functions-and-stability/MF-12/lean/reviews/statement-review-snapshot/formalization.yaml')
x=yaml.safe_load(old.read_text())
x['project']['name']='IE-14: sharp complex cyclic tridiagonal GEPP growth'
x['project']['description']='Full all-order sharp growth factor F(n+1)+1 for complex cyclic tridiagonal matrices under every legal partial-pivoting tie path; explicit rational attainment and genuine real supremum.'
x['sources']=[{'title':'IE-14 — Sharp growth for cyclic tridiagonal matrices','id':'https://github.com/sidneyholden1/OpenProblemsInNLA/blob/2eef31b5e5d33279ef2922a090f105c20e1b03fb/linear-systems-and-elimination/IE-14/README.md','type':'web-post','location':'Complete original problem statement','relationship':'formalizes','author_endorsement':'not-contacted'}, {'title':'Sharp growth for cyclic tridiagonal partial pivoting','authors':['Matthew J. Colbrook'],'id':'https://github.com/sidneyholden1/OpenProblemsInNLA/blob/2eef31b5e5d33279ef2922a090f105c20e1b03fb/references/colbrook-recovered-2026-09-11/manuscripts/IE-14.tex','type':'manuscript','location':'Theorem 1 and complete Sections 2–4','relationship':'formalizes','author_endorsement':'not-contacted','note':'Authorship attributed by the source to Matthew J. Colbrook, Cambridge. Substantial AI assistance and reconstruction disclosed; Higham retains original-target credit.'}]
x['related_formalizations'][0]={'id':'https://github.com/sidneyholden1/OpenProblemsInNLA/tree/736845bc/linear-systems-and-elimination/IE-15/lean','relationship':'other','note':'Padded active-state and exact Schur proof layout studied. IE-15 is real rook pivoting; IE-14 independently defines complex column-only partial pivoting and does not assume its bound.'}
x['automation']['methods'][0]['prompting_notes']='Full numerical statements first, two independent nonauthor approvals before proof, derive the two-row front from actual sparsity and row labels, minimize computation using exact complex triangle inequalities and Fibonacci recurrences. LeanCert kernel audits; no unnecessary interval calculations.'
x['status']['scope']='Statements only; four intended Challenge placeholders. No Solution or mathematical proof implementation. Two independent statement reviews, complete proof, final nonauthor reviews and actual Linux Comparator required; canonical status unchanged.'
names=['upper_bound','rational_attainment','sharp_maximum','original_target']
x['status']['main_results']=[{'declaration':'NLA.IE14.'+n,'file':'Challenge.lean','sorry_count':1,'comparator_config':'comparator.json','literature_dependencies':[]} for n in names]
x['fidelity']['divergences']='Full original target retained for every n≥4 over complex matrices, nonsingular with both cyclic corners nonzero. Actual fixed-order GEPP row swaps and Schur complements, every column-maximal pivot tie and every active entry. Explicit source rational family is embedded in the complex field; actual initial maximum and pivot admissibility are conclusions. The genuine real supremum comes with nonemptiness, boundedness and exact attainment. No front, realness, normalization or deterministic-tie assumption is inserted.'
x['review']['status']='statement-review-pending'
x['review']['notes']='Two independent nonauthor statement approvals and successful Challenge typecheck required before mathematical proof implementation. Independent final reviews and actual isolated Linux Comparator pending.'
x['alignment']=[{'source':s,'declarations':['NLA.IE14.'+n]} for n,s in zip(names,['Universal complex all-path upper bound','Actual rational attaining matrix and legal pivot path','Attained sharp bound over the full admissible set','Canonical all-order genuine-supremum target'])]
x['acknowledgements']='Mathematics attributed in the source to Matthew J. Colbrook, Cambridge; Higham retains the original problem and tridiagonal comparison credit. Formalization: Sidney Holden with OpenAI Codex assistance. Mathlib, LeanCert, Comparator and formalization.yaml retain licenses and credit. No novelty, external human review or author endorsement claimed.'
Path('formalization.yaml').write_text('# yaml-language-server: $schema=https://raw.githubusercontent.com/mathlib-initiative/formalization.yaml/99c678e569c7c4c0772db297c5ddd5e4c9b6322e/schema/v0.4.schema.json\n'+yaml.safe_dump(x,sort_keys=False,allow_unicode=True,width=100))
