import Mathlib.Analysis.Matrix.Order
import Mathlib.Analysis.CStarAlgebra.Unitary.Maps
import Mathlib.LinearAlgebra.Matrix.SchurComplement
#check mem_unitary_iff_star_mul_self
#check unitary.mem_iff
#check Unitary.val_star_mul_self
#check Unitary.star_mul_self
#check CStarRing.norm_coe_unitary_mul
#check CStarRing.norm_mul_coe_unitary
#check Matrix.fromBlocks_smul
#check Matrix.smul_fromBlocks
#check Matrix.fromBlocks_one
#check Matrix.fromBlocks_sub
#check Matrix.fromBlocks_add
#check Matrix.fromBlocks_conjTranspose
#check Matrix.fromBlocks_multiply
#check Matrix.unitaryGroup
#check Matrix.IsHermitian.smul
#check Matrix.PosSemidef.smul
#check Matrix.PosSemidef.diag_nonneg
#check IsStrictlyPositive.spectrum_pos
