from pathlib import Path
import hashlib,json
P=Path(__file__).resolve().parent.parent
sha=lambda f:hashlib.sha256((P/f).read_bytes()).hexdigest()
receipt={'phase':'statements only; no proof implementation','base_commit':'45c59bce549bbd90aef325901a9ebeefc270a1c0','fresh_https_main_at_setup':'45c59bce549bbd90aef325901a9ebeefc270a1c0','build_command':'PATH=/private/tmp/nla-20260922-runtime/lean-4.33.1-darwin_aarch64/bin:$PATH lake build Challenge','build_exit_code':0,'build_jobs':2401,'expected_challenge_placeholders':4,'definition_probe_exit_code':0,'metadata_draft_exit_code':0,'source_diagnostic_exit_code':0,'source_diagnostic_checks':31,'source_diagnostic_attribution':'Rerun of retained independent source Gaussian-integer polynomial checker, with source/output paths adapted; not newly independent authorship and not a Lean proof.','build_log_sha256':sha('verification/statement-build-final.log'),'definitions_probe_sha256':sha('verification/DefinitionsProbe.lean'),'limitations':'Original failed Definitions notation diagnostic retained in statement-build.log; final corrected boundary passes. No Solution implementation, final review or Linux Comparator claim.'}
(P/'verification/statement-local.json').write_text(json.dumps(receipt,indent=2)+'\n')
files=['NLA/MF22/Definitions.lean','Challenge.lean','NUMERICAL_TARGETS.md','README.md','formalization.yaml','comparator.json','lean-toolchain','lakefile.toml','lake-manifest.json','LICENSE','../README.md','../solution.md','../solution.tex','../../../references/stepaniants-mf22-2026-09-11/verification/MF-22-independent-review.md','verification/statement-build-final.log','verification/statement-local.json','verification/DefinitionsProbe.lean','verification/definitions-probe.log','verification/check_draft_metadata.py','verification/metadata-draft.log','verification/source_exact_check.py','verification/source-exact-check.json','verification/source-exact-check.log']
out={f:sha(f)for f in files}
(P/'reviews/statement-source-hashes.json').write_text(json.dumps(out,indent=2)+'\n')
print(json.dumps({'files':len(files),'manifest_sha256':sha('reviews/statement-source-hashes.json'),'status':'Ready for two independent nonauthor reviews; no proofs'},indent=2))
