from pathlib import Path
import json,hashlib,sys
scopes={'MI-19':'the full complex PSD q-permanent subset conjecture negation','MI-21':'the full geometric-mean inequality for unitarily invariant norms conjecture negation','MI-29':'the full original modulus determinant inequality conjecture negation','RA-03':'the full original squared Frobenius expected-error conjecture negation, excluding stronger-constant and unsquared-error extras','RA-07':'the full original convexity inequality for every positive real tuple and the stated interior index range; no nonpositive-input extension or enlarged index range is claimed'}
for p in json.load(open('/private/tmp/nla-fifth-five/projects.json')):
 if p['id'] not in sys.argv[1:]:continue
 a=Path(p['root'])/'docs/lean/reverification-2026-09-14'/p['id'];e=json.loads((a/'referee-2-operational-checks.json').read_text());assert e['verdict']=='PASS'
 t=f'''# {p['id']} — independent operational referee 2

**PASS — actual isolated Linux Comparator and retained evidence correspondence.** No material blockers.

Independent AI reviewer `/root/iv06_statement_referee_2`, 2026-09-14. The coordinator retrieved the GitHub API receipts and archive; I independently checked their internal identities, the archive digest/contents, exact immutable Git inputs and actual execution/control logs. I did not make a fresh remote API query or execute another remote job. This review concerns the successful run described below; it does not substitute historical verification for this campaign.

- Run [{e['run_id']}](https://github.com/sidneyholden1/OpenProblemsInNLA/actions/runs/{e['run_id']}), successful attempt {e['attempt']}, repository `sidneyholden1/OpenProblemsInNLA`.
- Exact verified commit `{e['verified_commit']}`.
- Artifact ID `{e['artifact_id']}`; original ZIP SHA-256 `{e['artifact_sha256']}`.
- {e['input_count']} complete project inputs independently matched to the exact Git tree/blob roster, result.json and current project bytes; {len(e['active_source_sha256'])} retained active source/config copies also matched.
- All {len(e['config']['theorem_names'])} configured exports appear in the same order in both actual Challenge and Solution exports, with no definition exceptions and only `propext`, `Classical.choice`, `Quot.sound` permitted.

The run/head SHA, successful attempt, artifact workflow-run identity, artifact ID/name and repository all agree across the saved API receipts, collector receipt, result.json and project inventory. The original ZIP passes CRC testing, its exact SHA-256 equals the GitHub API artifact digest and its size equals the receipt. Every extracted file is byte-identical to its ZIP member, with no extra or missing files. All {len(e['zip_members'])} member hashes and all {e['input_count']} immutable Git blob identities and SHA-256 values are retained in `referee-2-operational-checks.json`. This includes historical nested project inputs in their original Git ancestry; it does not imply their old verification results were adopted or independently rerun.

I checked the active proof dependency closure against my preceding hash-bound proof review. The frozen mathematical sources are unchanged from preserved base `deb549fa9ddd6b119e6c59016f268237e645dfa2`; that is deliberately not a claim that this source is today's main branch. George Stepaniants's existing formalization credit and the source mathematical attribution are preserved.

The actual comparator.log records Challenge build/export, Solution build/export, then **Running Lean default kernel on solution**, kernel acceptance and final Comparator acceptance with exit 0. This establishes the operational statement/axiom comparison for every listed theorem; an author's PASS label alone was not used. The kernel-control log actually executes Comparator.runBuiltinKernel: the honest inductive/quotient fixture is accepted, an invalid raw proof is rejected by the kernel for a type mismatch, and a mismatched Quot.lift is rejected by the quotient post-check. The five Comparator regression cases all have their required actual rejection/acceptance results. In particular, the dedicated type-mismatch fixture rejects a theorem-statement mismatch, and the illegal-helper fixture rejects a forbidden axiom. Separate complete runs reject sorryAx and the generated native_decide axiom with exit 1. The legacy fixture named simple_kind_mismatch reaches the illegal-helper axiom rejection; I do not misdescribe that fixture's actual output as an independent kind-only rejection. The simple_mismatch fixture supplies the actual constant-kind mismatch rejection.

The saved attempt-jobs receipt identifies the successful per-project verification job at the exact attempt and commit. The separate workflow job named `checker-controls` was skipped. Its skip does not stand in for execution: the per-project artifact retains the actual executed kernel, comparator, axiom and sandbox control logs inspected above and below. Artifact creation time falls within the successful verification job, and the selected artifact exactly matches the all-run-artifacts API receipt.

Both build and export sandbox modes run successfully while their negative probes fail as intended. Outside-project writes, truncation, creation and symlink escapes are denied. Build alone can write its designated .lake; export cannot. User, PID, mount, network, IPC and UTS namespaces are private; the host parent is absent from private /proc; loopback is unreachable; AF_UNIX creation is denied; effective capabilities are empty and no_new_privs is set. Nested namespace write attempts are rejected. Unknown options and unintended/relative write allowances are rejected with exit 2, and the original external/export fixtures stay unchanged. These are the actual per-project execution logs, not merely sandbox configuration assertions.

The repository workflow, harness and source-lock bytes were matched to the tested Git commit. The source-lock SHA-256 equals both result and tool receipts; the pinned Forsythe commit is `{e['tool_receipt']['forsythe_commit']}`, and the actual receipt identifies Lean 4.33.1 x86_64 Linux. All {len(e['dependency_revisions_checked'])} dependency revisions in the exact Lake manifest appear as checked-out revisions in the successful dependency log, including pinned Mathlib and LeanCert. Checker binary/bootstrap identities are attested by the retained harness receipt; binaries are not retained for independent rehashing. That limitation is explicit and separate from the source/hash/log checks performed here.

The source-fidelity and mathematical-scope verdict remains the separate STATEMENT-REFEREE-2.md and PROOF-REFEREE-2.md. This operational approval does not enlarge the target: {scopes[p['id']]}.

Machine evidence SHA-256: `{hashlib.sha256((a/'referee-2-operational-checks.json').read_bytes()).hexdigest()}`. The evidence includes exact archive-member hashes, API-receipt hashes, all project Git input hashes, active-source correspondence, every export, dependency revisions, control-log hashes and harness hashes. Original inputs and logs were not modified.
'''
 (a/'OPERATIONAL-REFEREE-2.md').write_text(t);(a/'referee2_write_operational.py').write_bytes(Path(__file__).read_bytes());print(p['id'],'operational report PASS')
