from pathlib import Path
import json,hashlib,subprocess,re,shutil
H=lambda b:hashlib.sha256(b).hexdigest()
notes={
'MI-19':'''The two exports cover a completely admissible counterexample and the negation of the original all-dimension, all-complex-Hermitian-PSD, all-q-in-[0,1], all-nonempty-proper-subset assertion. inversionCount uses every ordered index pair with i<j and reversed images. The identical exponent is retained in the restricted sum, whose filter is actual setwise image equality. The interior paper index 2 is correctly Fin index 1. Natural powers retain 0^0=1. Neither initial-segment reordering nor a product of smaller q-permanents replaces the target.

Mathlib PosSemidef is Hermitian symmetry and nonnegative quadratic form on all finitely supported complex vectors, hence all vectors in finite dimension. ComplexOrder compares real parts at equal imaginary parts. The counterexample explicitly requires both sums to have zero imaginary part, so its strict inequality cannot exploit incomparable nonreal numbers. In the generic Hermitian setting, conjugating permutation terms pairs sigma with sigma inverse; their inversion counts agree and the preserving set is inverse-closed, consistent with the source's real-valued comparison. No reality premise weakens the target.

My exact independent enumeration gives the full source polynomial from all 24 permutations and the restricted polynomial from exactly six permutations, using the original ordering. The exact Gram product equals A, and at q=7/8 full minus restricted is -3235575/16384. The optional rank-two and small positive-definite perturbation extensions are not formal targets. Finite permutation equivalence and exact fixed-point evaluation are an appropriate small proof route; only the final scalar sign needs the requested LeanCert check. A proved permutation enumeration and the Gram-to-complex-PSD bridge remain proof obligations.''',
'MI-21':'''The three exports retain every positive dimension and number of summands, arbitrary complex PD families, all original real parameters including t endpoints, and every unitarily invariant complex matrix norm. The custom norm predicate includes nonnegativity, definiteness, triangle inequality, homogeneity for every complex scalar and independent left/right unitary invariance. Thus it describes the full intended norm class. The explicit Euclidean continuous-linear-map operator norm is a genuine member only after the unconditional first export is proved; no norm property or eigenvalue is assumed.

CFC.rpow is the actual unital continuous functional calculus on the nonnegative spectrum. The geometric mean keeps A^(1/2), A^(-1/2) B A^(-1/2), its t-power and final A^(1/2) in exactly that noncommuting order. The right side retains every factor and exponent. Positive definite inputs ensure negative half powers have no zero spectral singularity; p>0 ensures the outer reciprocal is defined. The full conjecture is not restricted to integer powers, diagonal matrices or the selected norm.

Independent rational checks prove S is a symmetric involution, C²+E²=I, and all four input leading principal minors are positive. For each of the two actual mean candidates I checked det-ratio delta², the positive h, the positive matrix Q and the exact scaled Riccati equation Q base^(-1) Q=h D. Their candidate squares add to the exact displayed L; the second equals the conjugated first. L(1,-4)=1351000/1350907*(1,-4), with strict gap 93/1350907. The actual CFC identities remain explicit conclusions in counterexample, preventing a rational candidate from substituting for the spectral mean. A positive-root uniqueness argument can connect the Riccati data to CFC without numerical square roots. Aggregates I make the actual right matrix I for every p>0; one p suffices for the full negation. Known narrower parameter theorems are outside the claim.''',
'MI-29':'''The five exports preserve the full canonical quantifiers: every positive dimension, every complex PD A, invertible Hermitian B (including indefinite B), and all nonnegative real k,p. Both actual determinants are compared in ComplexOrder, with the generic comparison_positive_real export requiring their zero imaginary parts and strictly positive real parts from the original hypotheses. No positivity/commutation assumption on B, fixed dimension, integer-only exponent restriction or candidate spectral data weakens the conjecture.

Explicit CFC.rpow uses the unital spectral operation; its exponent-zero result is I on PSD matrices, unlike the separate nonunital power. matrixModulus is actual CFC.abs = CFC.sqrt(star X*X); matrix star is conjugate transpose and MatrixOrder is PSD order. The unconditional natural-power and modulus-eighth-power exports require the real analytic bridge before rational powers can be used. Invertibility is actual IsUnit in the square matrix ring. The witness's det B=-1/125 and opposite signs of two diagonal quadratic forms establish admissibility and genuine indefiniteness as conclusions.

I independently recomputed the two rational determinants after the required modulus reductions, obtaining exactly the displayed values and right-minus-left 21036678407451/156250000000000>0. Independent determinant polynomial expansion also recovers coefficients 0,2089017/16,-31188746592549/1024,0. The products BA²B and AB²A are distinct and remain in the correct order. Generic CFC identities followed by repeated squaring and exact 3x3 determinants avoid approximate roots or interval searches. All matrix/CFC connections and the generic determinant positivity remain proof obligations. The singular-input extension, established k=2 theorem and positive-B variants are expressly excluded without narrowing the canonical target.''',
'RA-03':'''The four exports retain every positive rectangular dimension, every complex input, and every 1≤k≤min(m,n). The process samples a joint entry with its current conditional norm-square weight, not independent row and column samples. The recursive history law recomputes probabilities after every actual rank-one cross update and sums every ordered history. none has mass one exactly at zero and sends the residual to zero. A zero entry at a nonzero residual has mass zero, so its identity update only totalizes an unused outcome. Invalid later histories retain zero product mass. Dimension-zero normalization is meaningful via the absorbing label, although the conjecture uses positive dimensions.

frobeniusSq is the sum of actual complex normSq; its first export identifies it with the explicitly scoped Frobenius matrix norm squared. Matrix.toEuclideanLin acts by the actual rectangular matrix on L2 spaces. Mathlib singularValues are the square roots of sorted eigenvalues of the true adjoint composition, with multiplicity and eventual zero. The range [k,min(m,n)) is exactly the source's one-based tail j>k. The target never substitutes a candidate best approximation or unordered spectrum. All conditional and history masses must be proved nonnegative and normalized unconditionally; this prevents a custom unnormalized sum from masquerading as expectation.

I independently computed all four cross updates, masses 2/5,1/10,1/10,2/5 and errors 9/4,9,9,9/4. The actual Gram candidate has characteristic polynomial (x-9)(x-1) and the two independent eigenvectors, giving candidate ordered singular values 3,1. Expected one-step error is 18/5 and the desired bound is 2; actual sorted singular-value identification remains an explicit proof obligation. Additional rational history tests cover zero absorption, zero entries, rectangular data and multiple lengths, but do not prove generic normalization. The source's all-rank sharp 4^r and Cholesky/correlation results were read and are excluded. The one-step counterexample still negates the full original assertion.''',
'RA-07':'''The six exports retain the full affirmative scalar question for all n≥3, every strictly positive real tuple, and 2≤j≤n-1, with no sorting, separation, normalization, root-factorization or distinctness assumptions. elementarySymmetric is the actual powersetCard subset product sum. The endpoint and positivity export must establish e0=1, oversized values zero and every admissible denominator positive. Thus total real division and natural subtraction cannot create a spurious endpoint result. The generating polynomial is the actual product of (1+lambda_i X) and the derivative is actual iterated polynomial differentiation.

The factorization export is unconditional for every d≤n: positive constant scale, exact degree n-d, exactly n-d positive reciprocal-root factors and polynomial equality. It preserves multiplicities. At d=n the empty tuple describes a positive constant, including n=0 in this auxiliary statement. Gauss–Lucas provides root-set containment only for a nonconstant complex polynomial; a later proof must separately establish splitting, nonzero derivatives, exact degree and multiplicity before extracting the real factorization. This is a legitimate replacement for source Rolle arguments, not an assumption of their conclusion.

The actual second-difference index uses derivative order j-1 and m=n-j+1≥2. Denominator s1*(s1²-s2) is required strictly positive; pairGap counts each a<b exactly once and may vanish. At j=n-1 the derivative has degree two, its third derivative vanishes and F_n=0. The smallest canonical n=3 is this same endpoint. Repeated/all-equal spectra remain included with weak convexity, not an unjustified strict assertion.

I independently reconstructed subset generating coefficients, exact pair identities and denominators on all tuples from {1/2,1,3} through dimension six, including empty/equal tuples and every canonical index. These are feasibility diagnostics only. The final theorem and certificate require all original ratios and an actual derivative factorization, so finite tests cannot discharge them. Mathlib esymm_map_val and coeff_iterate_derivative are appropriate existing bridges. Exact finite-sum algebra and root geometry leave no interval calculation; LeanCert may provide kernel trust auditing without an artificial point certificate. The source's strict monotonicity, extra index-one convexity, sampling expectation, Jensen and stable-rank applications are outside the canonical scalar target.'''
}
libs={'MI-19':['Analysis/Complex/Order.lean','LinearAlgebra/Matrix/PosDef.lean','GroupTheory/Perm/Fin.lean'],'MI-21':['Analysis/Matrix/Order.lean','Analysis/SpecialFunctions/ContinuousFunctionalCalculus/Rpow/Basic.lean','Analysis/CStarAlgebra/Matrix.lean','LinearAlgebra/Matrix/PosDef.lean'],'MI-29':['Analysis/Matrix/Order.lean','Analysis/SpecialFunctions/ContinuousFunctionalCalculus/Rpow/Basic.lean','Analysis/SpecialFunctions/ContinuousFunctionalCalculus/Abs.lean','Analysis/Complex/Order.lean'],'RA-03':['Analysis/Matrix/Normed.lean','Analysis/InnerProductSpace/PiL2.lean','Analysis/InnerProductSpace/SingularValues.lean'],'RA-07':['Algebra/Polynomial/Derivative.lean','RingTheory/MvPolynomial/Symmetric/Defs.lean','Analysis/Complex/Polynomial/GaussLucas.lean']}
for e in json.load(open('/private/tmp/nla-fifth-five/projects.json')):
 root=Path(e['root']);rel=Path(e['project']);p=root/rel;a=root/'docs/lean/reverification-2026-09-14'/e['id'];names=['README.md','NUMERICAL_TARGETS.md','Challenge.lean','comparator.json','formalization.yaml','lean-toolchain','lake-manifest.json','lakefile.toml'];sources=[str(rel.parent/'README.md'),'docs/lean/REVIEW.md']+[str(rel/n) for n in names]+[str(rel/'NLA'/e['id'].replace('-','')/'Definitions.lean')]
 if e['id'].startswith('MI'):sources += [str(rel.parent/n) for n in ['solution.md','solution.tex']]
 else:sources += ['references/colbrook-random-pivoting-2026-09-11/manuscripts/sharp_random_pivoting.tex' if e['id']=='RA-03' else 'references/colbrook-transfer-2026-09-11/manuscripts/01_volume_sampling_convexity.tex']
 hashes={}
 for f in sources:
  data=subprocess.check_output(['git','-C',str(root),'show',e['base']+':'+f]);q=root/f
  if q.exists():assert q.read_bytes()==data,(e['id'],f)
  hashes[f]={'sha256':H(data),'bytes':len(data),'read_method':'local source and immutable Git comparison' if q.exists() else 'git show immutable preserved source'}
 cfg=json.loads((p/'comparator.json').read_text());decls=re.findall(r'^theorem\s+(\w+)',(p/'Challenge.lean').read_text(),re.M);assert cfg['theorem_names']==['NLA.'+e['id'].replace('-','')+'.'+n for n in decls];assert cfg['definition_names']==[] and set(cfg['permitted_axioms'])=={'propext','Classical.choice','Quot.sound'}
 build=json.loads((a/'challenge-local.json').read_text());log=(a/'challenge-local.log').read_bytes();assert build['exit_code']==0 and H(log)==build['log_sha256'];assert log.decode().count('declaration uses `sorry`')==len(decls) and 'Build completed successfully' in log.decode()
 deps={f:H((p/'.lake/packages/mathlib/Mathlib'/f).read_bytes()) for f in libs[e['id']]};num=json.loads((a/'referee-2-numerical-checks.json').read_text());assert num['verdict']=='PASS'
 evidence={'verdict':'PASS','phase':'statement only before proof inspection','reviewer':'/root/iv06_statement_referee_2 (independent AI agent)','preserved_source_base':e['base'],'observed_upstream_main_not_source_base':e['upstream_current_main_observed'],'source_hashes':hashes,'actual_imported_semantics_sha256':deps,'exports':cfg['theorem_names'],'numerical_diagnostics':num,'numerical_evidence_sha256':H((a/'referee-2-numerical-checks.json').read_bytes()),'numerical_generator_sha256':H((a/'referee2_numerics.py').read_bytes()),'coordinator_challenge_build':build,'coordinator_receipt_sha256':H((a/'challenge-local.json').read_bytes()),'no_active_proof_or_solution_inspected':True,'historical_metadata_claims_not_reaudited':True}
 (a/'referee-2-statement-checks.json').write_text(json.dumps(evidence,indent=2)+'\n')
 report=f'''# {e['id']} — independent statement referee 2

**PASS — approved exact statement boundary.** No blocking mathematical fidelity, vacuity or numerical-data finding. Proof and actual isolated Linux Comparator remain separate future gates.

Independent AI reviewer `/root/iv06_statement_referee_2`, 2026-09-14. This applies `docs/lean/REVIEW.md` across full-target fidelity, mathematical meaning, degeneracies, numerical obligations, computation reduction, API reuse and attribution. It is the local Tau Ceti adaptation, not official Tau Ceti endorsement or external human peer review. I read the complete canonical page and complete informal source, actual Definitions and Challenge, numerical target plan, and the relevant scope/attribution/automation material in the project guide and manifest. No active Proof/Solution body or historical proof verdict was used as evidence for approval.

The authored source is preserved commit `{e['base']}`, deliberately not the observed older main `{e['upstream_current_main_observed']}`. This is reverification of existing George Stepaniants formalization, with original mathematical proof/counterexample credit retained for Matthew J. Colbrook and the original problem authors retained in the sources. No authorship, license or permanent problem ID was changed. Historical statement-stage notices and old published PASS claims remain historical, not evidence of a new proof or Linux run. Metadata's old verification claims were not reaudited at this phase.

## Full original target and obligations

{notes[e['id']]}

## Evidence and remaining gate

The independent exact Python reconstruction is retained as `referee2_numerics.py` with `referee-2-numerical-checks.json`; it uses rational/integer arithmetic and explicitly labels its diagnostic scope. It neither imports an author-supplied PASS nor proves the final universal theorem. Existing earlier reviewed CFC/matrix and finite-enumeration projects provide useful proof-organization examples; no mathematical theorem from those examples is introduced as an assumption. Targeted actual library semantics are hash-bound in the machine report. Full active-proof and transitive trust inspection must follow both statement approvals.

The coordinator's fresh pinned `lake build Challenge` returned exit 0 with exactly {len(decls)} deliberate placeholder warnings. I checked the matching receipt/log SHA-256 and complete export inventory; this build was the coordinator's, not my own, and establishes no proof. All {len(decls)} Challenge declarations match comparator.json, with no definition-name exceptions and only the standard three permitted final axioms. The zero proof-hole count in historical metadata excludes the isolated Challenge placeholders. Later proof review must check every actual export type/axiom closure and material LeanCert route; actual Linux Comparator must separately check statement identity, default kernel and rejection controls.

## Exact source binding

| Source | SHA-256 |
| --- | --- |
'''+''.join(f"| `{f}` | `{h['sha256']}` |\n" for f,h in hashes.items())+f"\nMachine statement-checks SHA-256: `{H((a/'referee-2-statement-checks.json').read_bytes())}`. It also binds the numerical generator/data, coordinator build and inspected library definitions. Approval applies only to these exact bytes.\n"
 (a/'STATEMENT-REFEREE-2.md').write_text(report);shutil.copy2(__file__,a/'referee2_statements.py');print(e['id'],'statement PASS',len(decls),flush=True)
