from pathlib import Path
import ast,hashlib,json
repo=Path('/tmp/nla-lean-fr12-worktree');p=repo/'frames-and-matrix-designs/FR-12/lean/verification/publication-2026-09-12';x=json.loads((p/'integrity.json').read_text())
sha=lambda f:hashlib.sha256(f.read_bytes()).hexdigest()
for f in p.glob('*.py'):ast.parse(f.read_text())
report=f'''# FR-12 publication preparation - 2026-09-12

**PASS: ready for independent parent publication review.** Prepared by
`/root/formal_review_standards`. This is a publication handoff, not an additional
mathematical proof review or a new Linux run. No publication commit, push or PR
was made. Parent review is the remaining publication gate.

## Verified result and publication scope

The unchanged proof at `{x['verified_revision']}` passed actual
[Linux run 34718277411](https://github.com/sgstepaniants/OpenProblemsInNLA/actions/runs/34718277411).
The already accepted [independent operational review](../linux-2026-09-12/OPERATIONAL-REVIEW.md)
has SHA256 `017e2a22ac88d153a311c7ef344fe0ac0b8d415f926d046da649e210585c53ac`.
Its outer manifest is `a9dfe074bd299c6826ffe7367f30c5154cf58440a4f88071b8a61ff27eda8aa1`.
All seven actual Comparator exports, default-kernel replay and fourteen
standard-three axiom assertions passed, with real standalone and per-project
controls. The nested Bubblewrap executable was denied UID-map creation before
its inner write; no inner-write execution is claimed.

Only FR-12 is promoted from Solved to Lean verified in the prepared working tree.
The canonical entry, project README, actual v0.4 manifest and RESOLVED record
name George Stepaniants with his Department of Computing and Mathematical
Sciences, California Institute of Technology affiliation. No email is added.
Ferber, Jain and Zhao retain their conjecture and prior-upper-bound credit.
The formally proved recurrence has factor `m!`; the stronger informal
`(2m-1)!!` recurrence is explicitly outside the exports. The actual finite
labeled real matrix count, complete quantitative lower bound and full original
universal conjecture negation are retained. LeanCert performs actual kernel
trust auditing of the exact proof; no interval certificate is claimed.

## Integration and preservation

A normal, conflict-free merge integrated freshly fetched upstream
`{x['upstream_base']}` into the candidate at
`{x['integration_commit']}`. The two parents are the verified candidate and
that upstream revision. Both commit names are George Stepaniants; both email
fields are entirely empty. This integration commit is the only commit made
in this task. The proof was verified at its original immutable revision, not
at the integration/publication wrapper revision.

The [executable integrity check](finish.py) and [bound result](integrity.json)
confirm:

- Exactly **135 of 137** verified inputs remain unchanged; the only two changed
  inputs are the current project README and formalization manifest. Their
  original metadata snapshots, all mathematical files, frozen statements,
  configurations, ten dependency pins, and all four referee reports are retained.
- All **256** operational evidence files remain byte-identical. The actual
  inventory is **255 bound files plus the outer manifest**; every nested
  manifest is included, and only the exact outer path excludes itself.
- All **216 other canonical pages**, all **217 permanent IDs**, the complete
  FR-12 original statement/reference tail and original informal proof sources
  are unchanged. All **11** previously verified upstream entries are retained.
- All **{x['unchanged_upstream_file_count']}** upstream files outside the seven intended existing
  publication/index files match their exact Git blob hashes. Shared tools,
  workflow, source lock and renderer are unchanged.
- Exactly nine tracked files differ from the integration commit: the canonical
  README/TeX/PDF, two project wrappers, RESOLVED, and three generated indexes.
  The retained Linux and publication evidence directories are additionally untracked.

Both required base validators pass (`origin/main`, `nla-upstream/main`).
Catalog generation validates all 217 IDs, all 17 permanent-ID tests pass,
all canonical math formatting is clean, and the actual pinned v0.4 validator
matches all seven configured exports. Final branch counts are **12 Lean
verified, 78 Solved, 55 Open and 72 Partially resolved**. They describe this
integrated branch, not unmerged proof PRs elsewhere.

## Documents and remaining review

The current canonical TeX and PDF were regenerated by the unchanged repo
renderer. All **three** pages were individually displayed and visually
inspected, with readable attribution, proof scope, export list, reproduction
commands and original statement/references. There are no clipping, overlap,
missing-glyph or overfull warnings. The final page contains the retained
reference continuation and dated historical search note. A status-line trailing
space caught by the first whitespace check was removed; the final render is
byte-identical at the PNG-page level to all three inspected images.

PDF SHA256: `{x['changed_file_sha256']['frames-and-matrix-designs/FR-12/problem.pdf']}`.
Canonical README SHA256: `{x['changed_file_sha256']['frames-and-matrix-designs/FR-12/README.md']}`.
Manifest SHA256: `{x['changed_file_sha256']['frames-and-matrix-designs/FR-12/lean/formalization.yaml']}`.
Integrity record SHA256: `{sha(p/'integrity.json')}`.

The parent should independently inspect the working-tree diff and the three
PDF pages before its authorized publication commit/push/PR. No new source
elaboration is needed for these wrapper edits; the complete previously
successful immutable proof/evidence binding is preserved. Disk exhaustion
interrupted the first fetch before any Git mutation; only disposable FR-12
Mathlib C-intermediate build files were removed, while all source, Git and
verification evidence stayed intact.
'''
(p/'PUBLICATION-HANDOFF.md').write_text(report)
(p/'write_handoff.py').write_bytes(Path(__file__).read_bytes())
outer=p/'EVIDENCE-MANIFEST.json';files={str(f.relative_to(p)):{'bytes':f.stat().st_size,'sha256':sha(f)} for f in sorted(p.rglob('*')) if f.is_file() and f!=outer}
outer.write_text(json.dumps({'purpose':'FR-12 publication preparation evidence; independent parent review pending','file_count':len(files),'files':files},indent=2)+'\n')
assert {str(f.relative_to(p)) for f in p.rglob('*') if f.is_file() and f!=outer}==set(files)
result={'handoff_sha256':sha(p/'PUBLICATION-HANDOFF.md'),'integrity_sha256':sha(p/'integrity.json'),'publication_evidence_manifest_sha256':sha(outer),'publication_bound_files':len(files),'publication_total_including_outer':len(files)+1,'pdf_sha256':x['changed_file_sha256']['frames-and-matrix-designs/FR-12/problem.pdf'],'integration_commit':x['integration_commit']}
print(json.dumps(result,indent=2))
