from pathlib import Path
import json,hashlib,re,subprocess,shutil
H=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
notes={
'FR-12':'''The seven exports are all connected to the original labeled-matrix target. Semantics encodes each real sign entry into Bool injectively, proving actual finiteness for every order (including zero); positive-order Gram semantics agree with Mathlib Hadamard matrices. Doubling computes all four block row inner products after an actual index equivalence. The two top blocks recover the input matrices; positive row norms and orthogonality make the rows injective, recovering the lower permutation. Thus the cardinal inequality counts actual subtype matrices with the genuine m! permutation factor. No quotienting, assumed injection or infinite-cardinality totalization remains.

Growth proves power-of-two nonemptiness from order one before using counts. Its factorial bound keeps the upper half through the actual Nat factorial theorem. Real-power multiplication and the explicit exponent identity prove the all-k lower bound, with natural/real casts and index shift preserved. Choosing a natural k>16C+2 supplies a strict exponent gap for every positive real C; log(2) is proved nonzero, and the selected dimension is proved positive and divisible by four. This refutes the full asymptotic bound. The stronger all-perfect-matching recurrence and a general Hadamard existence theorem are not claimed. The finite Boolean encoding, block arithmetic and scalar growth induction avoid expensive enumeration and numerical logarithm computation. LeanCert supplies explicit kernel trust audits only; there is no artificial interval certificate.''',
'MF-16':'''All nine exports are proved along the genuine complex-matrix route. Algebra evaluates the ordinary 16-letter palindrome and proves actual source matrix products/determinants. Complex positive definiteness follows from a diagonal positive form under an explicitly invertible LDL congruence; this is positivity for every nonzero complex vector, not just real vectors. CayleyHamilton proves an exact scalar polynomial division identity and applies the actual matrix characteristic-polynomial theorem to every determinant-three matrix. My independent recurrence diagnostic confirms both coefficient polynomials exactly. Polynomial expands the actual three Expr components and gives a bidirectional determinant/two-entry equivalence; the determinant premise for the power reduction is proved from component zero.

Numerical proves the actual full Krawczyk Boolean, preconditioner determinant, box radius and contraction bound by `decide +kernel`. I printed the real exported proof terms and all four auxiliary equality/comparison proofs: the acceptance equality is obtained by kernel reflexive Boolean reduction, not native evaluation. certified_root_proved materially applies LeanCert.Engine.krawczykCheck_sound to that exact acceptance theorem. The actual soundness theorem unpacks supported differentiation, center membership, a nonzero preconditioner determinant, strict contraction and self-map enclosure, derives a unique fixed point in the complete closed box, and converts it into an actual unique system zero using invertibility. The independently reconstructed whole-box rational AD diagnostics from statement review agree with the actual checker. No approximate root is assumed.

Recovery uses the palindrome's actual transpose identity and determinant 3^14 to recover the remaining matrix entry from the two checked entries; the nonzero leading target coefficient is discharged exactly. The box gives x>3, which both proves a positive leading minor and separates the recovered complex matrix from diag(3,1). All four entries, positive definiteness and distinctness reach counterexample; two genuine solutions then contradict the full all-word complex-PD uniqueness assertion. Local root uniqueness is not confused with global word uniqueness. Third solutions, degree theory and exponent thresholds remain excluded. The single radius-10^-7 three-dimensional box, exact characteristic-polynomial reduction and reusable real/complex bridges are appropriate computation reductions.''',
'TR-15':'''All seven exports preserve the complete common-generator Hankel tensor and full real H-eigenpair semantics. The lower contraction reindexes every ordered pair through an actual finite equivalence and computes all components for arbitrary real vectors. The upper contraction proves every tuple except the all-one tuple contributes zero, rather than assuming a selected tensor slice is the whole contraction. Its nonzero vector is checked by a coordinate. Strict positivity of the first lower contraction follows from its sum of squares and the nonzero-vector condition; every real lower eigenpair must consequently have positive eigenvalue even when its first vector coordinate is zero.

Nonvacuity is proved separately by continuity and the genuine intermediate-value theorem on [0,1]; strict endpoint signs yield an interior root and every coordinate of the resulting eigenpair is verified. The actual negative upper eigenpair materially includes negative_eigenvalue_certificate. Its printed term applies verify_strict_upper_bound_dyadic_checked at singleton [0,0], precision -53, depth 10; the separately printed Boolean checker proof is `of_decide_eq_true (id (Eq.refl true))`. The verifier checks domain validity and enclosure soundness before strict comparison. Full admissibility is supplied and the counterexample directly instantiates the original universal inheritance statement. No vacuous lower-eigenpair premise, tensor normalization, numerical root approximation or eigenvalue enumeration is used. Even-order inheritance and stronger Hankel-matrix positivity statements are outside scope.''',
'IE-18':'''The three exports cover exact recurrence data, an admissible spectral counterexample and the full four-step conjecture negation. Both residual-map evaluations follow the actual matrix-vector and dot-product definitions. Nonzero initial/intermediate vectors and exact positive denominators 61/50 and 1381/93025 prevent zero-branch or total-division artifacts. Actual squared norms and their ratio are computed from all coordinates.

The spectral proof uses the true diagonal spectrum, positive definiteness of both M and I-M, and exclusion of eigenvalue one. The actual Mathlib eigenvalue ordering is never guessed: membership in the spectrum bounds every chosen pair, while two unequal spectrum values supply distinct eigenvalue indices attaining the finite maximum. Thus pairMaximum is genuinely 1/121, including its multiplicity/index semantics. The Euclidean norm is the square root of the coordinate-square sum. The proof squares that already-squared pair bound again to 1/14641, compares it with 1920682/21289638243, and uses nonnegative norms to obtain the strict unsquared amplification gap. A genuine nonzero-vector member of the amplification set then contradicts IsGreatest's upper-bound obligation; no attainment of the true maximum is needed to refute the proposed one.

The material scalar theorem is invoked through `leancert (trust := kernel)`. Inspection of its actual printed term shows Mathlib NormNum exact rational-comparison constructors, including a reflexively checked integer inequality; it is not a dyadic interval certificate. This is an optimized exact arithmetic route within LeanCert, plus explicit kernel trust audits. It would be inaccurate to describe this project as using interval enclosure for this point. All quantities and bridges match the source counterexample; there is no diagonal restriction on the universal target.''',
'IE-19':'''The three exports give the admissible order-three counterexample with genuine inverses and nonsingularity, then negate both the original inequality and its equality-characterized sharpening. Entrywise bounds, real symmetry and all weak diagonal-dominance conditions are proved for the actual witness. Exact full matrix multiplication proves a right inverse for each matrix. Mathlib's actual isUnit_det_of_right_inverse and inv_eq_right_inv then establish nonsingularity and identify the totalized matrix inverse with those candidates. There is no assumed inverse or singular-case escape.

Every row's absolute scalar norm sum is computed exactly; Finset.sup_const with the explicit nonempty finite index set proves the actual finite maximum is 7/9 for the witness inverse and 5/4 for the comparison inverse. The comparison formula evaluates to 5/4 under parameters satisfying all source constraints. The strict gap then refutes the original universal inequality, which in turn refutes the conjunction with equality characterization. The source's additional sharp infimum/nonattainment theory is not claimed.

The material scalar gap uses `leancert (trust := kernel)`, but its actual printed proof is a Mathlib NormNum exact rational comparison and reflexive integer check, not an interval or dyadic verifier term. Kernel trust audits cover every export. Exact finite multiplication, all-row constant sums and the tiny rational inequality are appropriate reductions; approximate matrix inversion and larger numerical intervals are unnecessary.'''
}
extra_deps={
'FR-12':['mathlib/Mathlib/Data/Nat/Factorial/Basic.lean','mathlib/Mathlib/SetTheory/Cardinal/Finite.lean'],
'MF-16':['LeanCert/LeanCert/Engine/RootFinding/Krawczyk.lean','mathlib/Mathlib/LinearAlgebra/Matrix/Charpoly/Coeff.lean','mathlib/Mathlib/LinearAlgebra/Matrix/PosDef.lean'],
'TR-15':['mathlib/Mathlib/Topology/Order/IntermediateValue.lean','LeanCert/LeanCert/Validity/DyadicBounds.lean','LeanCert/LeanCert/Tactic/IntervalAuto/PointIneq.lean'],
'IE-18':['mathlib/Mathlib/Analysis/Matrix/Spectrum.lean'],
'IE-19':['mathlib/Mathlib/LinearAlgebra/Matrix/NonsingularInverse.lean']}
for e in json.load(open('/private/tmp/nla-fourth-five/projects.json')):
 r=Path(e['root']);p=r/e['project'];a=r/'docs/lean/reverification-2026-09-14'/e['id'];co=json.loads((a/'referee-2-consumer.json').read_text());assert co['exit_code']==0;assert H(a/'referee-2-consumer.log')==co['log_sha256'];assert H(a/'referee-2-consumer.lean')==co['script_sha256']
 gate=json.loads((a/'statement-gate.json').read_text())
 for f,h in gate['files_sha256'].items():assert H(r/f)==h
 active=json.loads((a/'referee-2-active-inputs.json').read_text())
 for f,v in active['files'].items():assert H(r/f)==v['sha256']
 modules={k:v for k,v in active['files'].items() if k.endswith('.lean') and not k.endswith('/Challenge.lean')}
 for f in modules:
  txt=(r/f).read_text();assert not re.search(r'\bsorry\b|\badmit\b|^axiom\s|native_decide|ofReduceBool',txt,re.M),f
 build=json.loads((a/'solution-local.json').read_text());assert build['exit_code']==0;assert H(a/'solution-local.log')==build['log_sha256']
 evidence=['statement-gate.json','referee-2-active-inputs.json','referee-2-consumer.lean','referee-2-consumer.log','referee-2-consumer.json','solution-local.json','solution-local.log','referee-2-numerical-checks.json','referee2_numerics.py','referee2_statements.py','referee2_consume.py']
 if e['id']!='FR-12':
  run=json.loads((a/'referee-2-numerical-terms.json').read_text());assert run['exit_code']==0;assert H(a/'referee-2-numerical-terms.log')==run['log_sha256'];evidence+=['referee-2-numerical-terms.lean','referee-2-numerical-terms.log','referee-2-numerical-terms.json','referee2_terms.py']
 if e['id']=='MF-16':
  run=json.loads((a/'referee-2-krawczyk-aux.json').read_text());assert run['exit_code']==0;assert H(a/'referee-2-krawczyk-aux.log')==run['log_sha256'];assert 'of_decide_eq_true (id (Eq.refl true))' in (a/'referee-2-krawczyk-aux.log').read_text();evidence+=['referee-2-krawczyk-aux.lean','referee-2-krawczyk-aux.log','referee-2-krawczyk-aux.json','referee-2-cayley-hamilton.py','referee-2-cayley-hamilton.json']
 deps={f:H(p/'.lake/packages'/f) for f in extra_deps[e['id']]}
 checks={'verdict':'PASS','phase':'independent proof source and local export consumer','reviewer':'/root/iv06_statement_referee_2','candidate_commit':e['commit'],'source_base':e['base'],'observed_current_main_not_source':e['upstream_current_main_observed'],'active_source_count':len(modules),'export_count':len(co['exports']),'export_axioms':co['exports'],'consumer_exit_code':co['exit_code'],'consumer_command':co['command'],'consumer_cwd':co['cwd'],'coordinator_solution_build_exit_code':0,'unchanged_frozen_statement_gate':True,'active_sources_equal_candidate_and_preserved_base':True,'targeted_imported_semantics_sha256':deps,'evidence_sha256':{f:H(a/f) for f in evidence},'linux_status':'separate pending operational review, not inferred from historical PASS'}
 (a/'referee-2-proof-checks.json').write_text(json.dumps(checks,indent=2)+'\n')
 report=f'''# {e['id']} — independent proof referee 2

**PASS — full frozen-target fidelity, proof-source audit and fresh independent local consumer.** No material blocking findings.

Reviewer: `/root/iv06_statement_referee_2`, independent AI agent, 2026-09-14. I applied `docs/lean/REVIEW.md` across source fidelity, mathematical correctness, degeneracies, computation reduction, library reuse and attribution. This is the local Tau Ceti adaptation, not official Tau Ceti endorsement or human peer review. Both independent statement approvals preceded this campaign's proof inspection.

This is reverification of George Stepaniants's existing AI-assisted formalization at preserved source `{e['base']}`, not newly authored work or the observed older main `{e['upstream_current_main_observed']}`. Candidate `{e['commit']}` preserves the reviewed mathematical bytes. Mathematical credit remains {'George Stepaniants; Ferber–Jain–Zhao retain their conjecture/prior-bound credit' if e['id']=='FR-12' else 'Matthew J. Colbrook, with the original problem and referenced authors credited in the canonical source'}. Author affiliation and Apache-2.0 notices are retained. No source, metadata or permanent ID was changed by this referee.

## Actual proof and full target

{notes[e['id']]}

## Independent evidence and limits

I read the complete active local mathematical dependency closure and every Solution wrapper ({len(modules)} Lean modules), excluding duplicated historical snapshots. The canonical/full informal sources, numerical targets and genuine definitions were read in the frozen statement review. Every frozen gate file was rehashed unchanged, and every active module was compared byte-for-byte with both the immutable candidate and preserved authored base. The exact paths, byte sizes and hashes are retained in `referee-2-active-inputs.json`.

The coordinator's fresh pinned macOS `lake build Solution` passed; I checked its exit-0 receipt and matching log hash. I then independently ran a fresh `lake env lean` consumer importing the actual Solution, querying all {len(co['exports'])} exported types, printing every transitive axiom closure and executing `#assert_trust kernel` on each export. That independent consumer returned exit 0. Every export has exactly `propext`, `Classical.choice`, `Quot.sound`; no sorry, native reduction or custom axioms appear. Actual printed types and the Solution proof routes agree with the approved Challenge boundary. Numerical terms and their actual checker evidence were inspected separately where used. Generator scripts are retained in this audit directory for reproducibility.

The imported Mathlib and LeanCert inspection is a targeted review of the actual semantic APIs and material soundness route, not a line-by-line reproof of every library dependency. All project proof bodies were read; the standard-axiom consumer supplies separate transitive trust coverage. This report does not establish isolated Linux Comparator identity, default-kernel execution or rejection/sandbox controls. Those require the separate actual operational audit; no historical success is substituted.

## Exports

'''+''.join(f'- `{n}` — type queried; standard-three axioms; kernel trust PASS.\n' for n in co['exports'])+'''
## Exact active source hashes

| Source | SHA-256 |
| --- | --- |
'''+''.join(f"| `{f}` | `{v['sha256']}` |\n" for f,v in modules.items())+f"\nMachine proof-checks SHA-256: `{H(a/'referee-2-proof-checks.json')}`. That report binds the gate, source manifest, fresh consumer scripts/receipts/logs, numerical evidence and coordinator build by exact hashes.\n"
 (a/'PROOF-REFEREE-2.md').write_text(report);shutil.copy2(__file__,a/'referee2_write_proofs.py');print(e['id'],'proof PASS',len(co['exports']),flush=True)
