"""Independently reproducible integer certificate for a 2x2 word counterexample.

Python standard library only. The derivative is generated by the product rule
on all 16 letters, without using the factored Jacobian formula.
"""
from __future__ import annotations
import argparse, json
from pathlib import Path

Matrix=tuple[int,int,int,int]
I:Matrix=(1,0,0,1)
ZERO:Matrix=(0,0,0,0)
BASIS:tuple[Matrix,...]=((1,0,0,0),(0,1,1,0),(0,0,0,1))

def add(A:Matrix,B:Matrix)->Matrix:return tuple(a+b for a,b in zip(A,B))
def mul(A:Matrix,B:Matrix)->Matrix:
    return (A[0]*B[0]+A[1]*B[2], A[0]*B[1]+A[1]*B[3],
            A[2]*B[0]+A[3]*B[2], A[2]*B[1]+A[3]*B[3])
def det2(A:Matrix)->int:return A[0]*A[3]-A[1]*A[2]
def det3(J:list[list[int]])->int:
    a,b,c=J
    return a[0]*(b[1]*c[2]-b[2]*c[1])-a[1]*(b[0]*c[2]-b[2]*c[0])+a[2]*(b[0]*c[1]-b[1]*c[0])
def evaluate(X:Matrix,B:Matrix,r:int):
    if r<1:raise ValueError('r must be positive')
    S=I; DS=[ZERO,ZERO,ZERO]
    word='XB'+'X'*r+'BX'
    for letter in word:
        M=X if letter=='X' else B
        DM=BASIS if letter=='X' else (ZERO,ZERO,ZERO)
        DS=[add(mul(D,M),mul(S,E)) for D,E in zip(DS,DM)]
        S=mul(S,M)
    if S[1]!=S[2] or any(D[1]!=D[2] for D in DS):raise ArithmeticError('Symmetry check failed')
    J=[[D[k] for D in DS] for k in (0,1,3)]
    return S,J,det3(J)
def main():
    ap=argparse.ArgumentParser();ap.add_argument('output',type=Path);ap.add_argument('--verify',action='store_true');args=ap.parse_args()
    X=(3,0,0,1);B=(1,4,4,17);r=12
    P,J,det=evaluate(X,B,r)
    if not (X[0]>0 and det2(X)>0 and B[0]>0 and det2(B)>0 and P[0]>0 and det2(P)>0):raise ArithmeticError('Positive-definiteness test failed')
    t=3;a=1;b=4;c=17;p=t**r;g=sum(t**k for k in range(r))
    bracket=(r+2)*(a*a*p*t+c*c+a*c*g*t)-(r-2)*b*b*(g*t+p+t)
    factored=p*t*(r+2)*(a*c-b*b)**2*bracket
    if det!=factored or det>=0:raise ArithmeticError('Negative determinant certificate failed')
    if det!=-11785057051824 or bracket!=-527992:raise ArithmeticError('Expected exact values differ')
    result={'word':'X B X^12 B X','coordinates':['X11','X12','X22'],
            'X0':[[3,0],[0,1]],'B':[[1,4],[4,17]],
            'P':[[P[0],P[1]],[P[2],P[3]]], 'jacobian':J,
            'jacobian_determinant':det,'det_X0':det2(X),'det_B':det2(B),'det_P':det2(P),
            'factored_bracket':bracket,
            'conclusion':'Armstrong--Hillar Corollary 11.1 gives at least two distinct real SPD solutions; separate interval certificates give at least three.'}
    if args.verify:
        if json.loads(args.output.read_text())!=result:raise ArithmeticError('Stored data differ from the exact regeneration')
    else:args.output.write_text(json.dumps(result,indent=2)+'\n')
    print('PASS:',det,'< 0; det(X0)=3, det(B)=1, det(P)=3^14.')
if __name__=='__main__':main()
