from pathlib import Path
from datetime import datetime,timezone
import hashlib,json,re,subprocess,collections,yaml
R=Path('/tmp/nla-lean-ra08-worktree');E=R/'randomized-and-low-rank-approximation/RA-08';P=E/'lean';O=P/'verification/publication-2026-09-13'
C='de6513d726e3f66d20730fdaef5ba99318ee7e8b';BASE='5830ed4fb06da0659414a3deb2a40ad327aca052'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();git=lambda *a:subprocess.check_output(['git',*a],cwd=R)
assert git('rev-parse','HEAD').decode().strip()==C and not git('diff','--name-only','HEAD') and not O.exists()
assert sha(P/'verification/root-operational-2026-09-12/ROOT-CHECKS.json')=='a1fb7ac0b4bfebb5cd1e536ac7b5d78f3beb82b6ca4d1486ca0f3c293d9b3c12'
inputs={}
for path in git('ls-tree','-r','--name-only',C,'--',P.relative_to(R).as_posix()).decode().splitlines():
 rel=str(Path(path).relative_to(P.relative_to(R)));h=hashlib.sha256(git('show',C+':'+path)).hexdigest();assert sha(P/rel)==h;inputs[rel]=h
assert len(inputs)==613
immutable={}
for name,num,h in [('linux-2026-09-12',792,'072e05a2022b16ffbf259ca5cfdf6b47929865aad70c8ba20d1a3ac38c31ce1b'),('root-operational-2026-09-12',6,'91e78bd9d0df6fc6d57461a6bf30f64dbc9f5e94262499cc5e88474dc26437b0')]:
 root=P/'verification'/name;out=root/'EVIDENCE-MANIFEST.json';assert sha(out)==h;d=json.loads(out.read_text());assert len(d['files'])==num
 actual={str(f.relative_to(root)) for f in root.rglob('*') if f.is_file() and f!=out};assert actual==set(d['files'])
 for rel,v in d['files'].items():
  f=root/rel;assert not f.is_symlink() and f.resolve().is_relative_to(root.resolve());assert sha(f)==v['sha256'] and f.stat().st_size==v['bytes']
 immutable.update({str(f.relative_to(P)):sha(f) for f in root.rglob('*') if f.is_file()})
assert len(immutable)==800
registry=json.loads((R/'problem_ids.json').read_text());counts=collections.Counter(re.search(r'^\*\*Status:\*\*\s+([^\n]+)',(R/path).read_text(),re.M).group(1).strip() for path in registry.values());assert counts=={'Lean verified':16,'Solved':76,'Open':53,'Partially resolved':72}
canonical=(E/'README.md').read_text();target=canonical[canonical.index('Let $`n\\ge2`$'):]
O.mkdir();(O/'archive').mkdir()
for n,dest in [('README.md','README.linux-candidate.md'),('formalization.yaml','formalization.linux-candidate.yaml')]: (O/'archive'/dest).write_bytes((P/n).read_bytes())
before=dict(utc=datetime.now(timezone.utc).isoformat(),candidate=C,base=BASE,project_inputs=inputs,immutable_operational_files=immutable,canonical_target_sha256=hashlib.sha256(target.encode()).hexdigest(),registry_sha256=sha(R/'problem_ids.json'),status_counts_before=dict(counts),publication_preparer='/root: disclosed proof coauthor, no independent mathematical review',expected_changed_candidate_inputs=['README.md','formalization.yaml'])
(O/'before.json').write_text(json.dumps(before,indent=2)+'\n')
canonical=canonical.replace('**Last checked:** 2026-09-11  \n**Status:** Solved  \n','**Last checked:** 2026-09-13\n\n**Status:** Lean verified\n',1)
old='Verification is independent agent review, not external human peer review or formal certification.';assert old in canonical;canonical=canonical.replace(old,'That dated manuscript review was independent agent review; the separate Lean verification below certifies the full original target. External human peer review is not claimed.',1)
section=r'''## Lean proof and verification evidence — 2026-09-13

**Formalization:** George Stepaniants, Department of Computing and Mathematical Sciences, California Institute of Technology, Pasadena, California, USA, with AI-agent assistance. **Matthew J. Colbrook retains authorship of the mathematical counterexample.**

The [fourteen formal exports](lean/Solution.lean) refute the complete original implication for all real symmetric PSD pairs, admissible concave functions, original dimensions/ranks/error parameters and permitted ordered eigenbases. The formal definitions use the genuine Euclidean operator norm and Mathlib continuous functional calculus. Truncations use the same selected eigenvectors, including repeated eigenspaces; admissibility allows $`f(0)>0`$. Existence of ordered spectral data and their actual CFC and norm meanings are proved.

For the unchanged six-dimensional source witness with $`t=1/65536`$ and $`f(x)=\min(x,1)`$, the input residual and both optimal tails equal $`t`$, whereas the transformed error is strictly larger. Exact compression, a degree-six polynomial minorant, genuine CFC order and a Rayleigh bound reduce the contradiction to a rational positive gap. The materially used LeanCert checker proves strict positivity in explicit kernel mode on a singleton; no interval subdivision or numerical spectral enclosure is needed. The source's larger contour-method ratio, separate Nyström sketch identity and ancillary nuclear-norm extensions are outside these fourteen exports.

Two independent statement approvals preceded implementation, and [two independent final mathematical reports](lean/README.md#review-and-checks-actually-performed) approved the complete frozen proof. The [actual Ubuntu run](https://github.com/sgstepaniants/OpenProblemsInNLA/actions/runs/34735273999) at immutable revision [de6513d7](https://github.com/sgstepaniants/OpenProblemsInNLA/tree/de6513d726e3f66d20730fdaef5ba99318ee7e8b/randomized-and-low-rank-approximation/RA-08/lean) passed all 17 jobs. All fourteen exports matched without definition exceptions; default-kernel replay, 59 standard-three axiom reports and both real control suites passed as a non-root user. The [independent operational audit](lean/verification/linux-2026-09-12/OPERATIONAL-REVIEW.md) and [coordinator acceptance](lean/verification/root-operational-2026-09-12/ROOT-CHECKS.json) bind all 613 submitted inputs and original evidence. Local Mac checks are separately identified. The [v0.4 manifest](lean/formalization.yaml), [numerical targets](lean/NUMERICAL_TARGETS.md) and [proof map](lean/PROOF_MAP.md) document the verified scope. The original mathematical statement and sources below are unchanged.

'''
assert canonical.count('Let $`n\\ge2`$')==1;canonical=canonical.replace('Let $`n\\ge2`$',section+'Let $`n\\ge2`$',1);assert canonical[canonical.index('Let $`n\\ge2`$'):]==target
(E/'README.md').write_text(canonical)
readme=(P/'README.md').read_text();old=readme.splitlines()[2];assert 'fourteen-export' in old and 'pending' in old
readme=readme.replace(old,'**The complete fourteen-export proof passed independent mathematical review and actual Ubuntu Comparator/default-kernel verification.** The [canonical problem](../README.md) records the full target as **Lean verified**. The immutable checked revision and evidence are documented below.',1).replace('## Reproduction and remaining gates','## Reproduction',1)
old='The unchanged default Lake target is `Challenge`; plain `lake build` checks the reference statements and does not prove them. Actual Ubuntu verification must run the pinned Comparator for all fourteen exports, default-kernel replay and both real control suites. Independent operational acceptance and publication review are also required before any canonical **Lean verified** promotion.'
assert old in readme
readme=readme.replace(old,'The unchanged default Lake target is `Challenge`; plain `lake build` checks the reference statements and does not prove them. Reproduce the authoritative check from the immutable revision using the [Linux workflow](../../../.github/workflows/lean-verification.yml) and [pinned checker instructions](../../../docs/lean/README.md). These run Comparator, default-kernel replay and both real control suites as a non-root Ubuntu user.',1)
readme+='''

## Actual Ubuntu verification and publication preservation

[Run 34735273999](https://github.com/sgstepaniants/OpenProblemsInNLA/actions/runs/34735273999) checked immutable candidate `de6513d726e3f66d20730fdaef5ba99318ee7e8b`. All 17 jobs and every step passed. Ubuntu 24.04 x86_64 ran the exact Lean 4.33.1, pinned Comparator/exporter and strict sandbox under UID 1001. It freshly checked out all ten dependency revisions and used 8,690 matching official Mathlib cache files. Challenge/Solution graph sizes were 2,710/3,161 jobs; this does not claim a full dependency-source rebuild.

Both export lists contain exactly the fourteen advertised declarations without definition exceptions. Default-kernel replay accepted the Solution; all 59 actual source axiom reports agree with the 59 explicit kernel assertions and contain exactly `propext`, `Classical.choice`, `Quot.sound`. The Solution phase has no warnings or admissions. Final referees' counts of 61/62 include additional local helper or consumer checks; their original reports remain unchanged.

The target and standalone checker jobs each executed actual sandbox probes, three raw-kernel controls, five Comparator fixtures and admission/native rejection controls. Actual bad proofs were rejected for `sorryAx` and `checked._native.native_decide.ax_1_1`. Nested Bubblewrap was denied UID-map setup before its inner write; this is not an observed inner-write denial or general sandbox-security proof.

The [independent operational audit](verification/linux-2026-09-12/OPERATIONAL-REVIEW.md) and [complete outer manifest](verification/linux-2026-09-12/EVIDENCE-MANIFEST.json) bind 792 files plus the outer file, including eight nested candidate manifests. All 613 retained candidate inputs match their committed Git blobs and the actual verifier receipt. Original project ZIP SHA256 is `b44731a25d3b3440bed0c15432043ccc6633fe8bd7e711d9f6d934cacfba5996`; control ZIP SHA256 is `ab70267cf3b05c74476a790c97aba10248e8bb5dd54c3f98aedaa25e9dcfa37e`. These agree with GitHub metadata and actual upload logs. The complete 217-log run archive is retained with a separately computed digest; no GitHub-published checksum for that log ZIP is claimed.

Operational reviewer `/root/mf16_final_referee` also served as independent final mathematical referee 2. Referee 1, `/root/leancert_examples`, later prepared candidate documentation. Root accepted the operational audit and prepared publication wrappers in its disclosed mathematical coauthor role. `/root/formal_review_standards` is the main proof coauthor. None of these additional roles increases the independent final mathematical referee count. [Root acceptance](verification/root-operational-2026-09-12/ROOT-CHECKS.json) and its complete inventory bind six files plus that outer manifest.

The actual run checks the immutable candidate, not these later wrappers. Publication changes only this README and five status/review fields in formalization.yaml among its 613 inputs. Both exact candidate wrappers are archived under [publication evidence](verification/publication-2026-09-13/archive/); all 611 other inputs, 793 Linux evidence files and seven root operational files remain unchanged. The 450 proof-freeze inputs, 39 statement inputs and ten original source snapshots remain preserved through the exact historical wrapper archives. Every nested manifest remains retained; the canonical original mathematical suffix and source manuscripts are unchanged. Earlier pending notices are historical phase records.

Independent publication review is required before a publication commit, normal fork push and separate upstream main PR. These wrappers claim no new proof execution, external human review, official Tau Ceti endorsement or new mathematical priority.
'''
(P/'README.md').write_text(readme)
path=P/'formalization.yaml';header=path.read_text().splitlines()[0];d=yaml.safe_load(path.read_text())
d['status']['scope']='Complete fourteen-export negative answer to the full original universal real-PSD concave spectral-transfer implication, retaining every function, parameter and selected eigenbasis and genuine Euclidean operator norm/CFC semantics. Two independent statement approvals preceded implementation; two independent final mathematical approvals and actual Ubuntu run 34735273999 at '+C+' passed. Independent operational review and root acceptance bind all 613 inputs and both actual control suites. Canonical status is Lean verified; stronger contour-ratio, separate Nystrom identity and ancillary nuclear extensions remain outside these exports.'
d['review']['status']='agent-reviewed; Linux-Comparator-and-default-kernel-verified'
d['review']['notes']='Both independent statement approvals preceded implementation; both independent final mathematical referees approved the full original target and actual CFC/norm/order/spectral/truncation proof chain. Fresh local referee checks had 61 and 62 standard-three reports, including additional helper or consumer inspections, using private macOS target prefixes and read-only clean pinned MI22 dependencies. Actual Ubuntu run 34735273999 at '+C+' passed all 17 jobs and steps, matched all fourteen exports without definition exceptions, accepted default-kernel replay, and emitted 59 embedded kernel/standard-three reports. Both actual sandbox/kernel/Comparator/admission/native suites passed as UID1001. The material LeanCert strict-upper checker for zero on singleton [0,0] below the exact rational gap feeds the real CFC Rayleigh contradiction and full negation; no interval subdivision or numerical spectral enclosure. Ten dependencies were freshly checked out with8690 matching official Mathlib cache files, not a full dependency-source rebuild. Nested Bubblewrap was denied UID-map setup before any inner write. Independent operational reviewer /root/mf16_final_referee is also finalref2; /root/leancert_examples is finalref1 and later candidate-document preparer. Root is a mathematical coauthor, independently accepts the operational evidence and prepares publication wrappers, not an independent final mathematical referee. Operational report SHA256 2b16b9952c15f070810756159990cc90745afaa7ad5ac22c3d022cce6b91cffe and outer072e05a2022b16ffbf259ca5cfdf6b47929865aad70c8ba20d1a3ac38c31ce1b bind792files plus outer, including eight nested manifests; root checks SHA256 a1fb7ac0b4bfebb5cd1e536ac7b5d78f3beb82b6ca4d1486ca0f3c293d9b3c12 accept the exact run and all613inputs. Only two wrappers/five status-review fields change; exact originals archived, all611otherinputs/793Linuxfiles/sevenrootfiles and every frozen mathematical/source input preserved. Separate publication review remains required. Local checks are not labeled Linux; no external human review, official Tau Ceti endorsement or mathematical priority is claimed.'
d['review']['linux_verification']['status']='passed; independently audited and root accepted'
d['review']['linux_verification']['note']='Actual run https://github.com/sgstepaniants/OpenProblemsInNLA/actions/runs/34735273999 at '+C+'. Fourteen matched exports, 59 standard-three reports, default-kernel replay and both real controls passed. Complete original artifact ZIPs, 217 run logs and exact613-input candidate snapshot remain at verification/linux-2026-09-12 with OPERATIONAL-REVIEW.md and full EVIDENCE-MANIFEST.json. See verification/root-operational-2026-09-12/ROOT-CHECKS.json for coordinator acceptance. The immutable candidate is verified; its exact wrappers are archived before this publication update.'
# Keep count phrases readable while leaving all other manifest structure intact.
for key in ['notes']:
 for a,b in {'with8690':'with 8690','outer072':'outer 072','bind792files':'bind 792 files','all613inputs':'all 613 inputs','all611otherinputs/793Linuxfiles/sevenrootfiles':'all 611 other inputs, 793 Linux files and seven root files','finalref2':'final referee 2','finalref1':'final referee 1','UID1001':'UID 1001'}.items():d['review'][key]=d['review'][key].replace(a,b)
d['review']['linux_verification']['note']=d['review']['linux_verification']['note'].replace('exact613-input','exact 613-input')
path.write_text(header+'\n'+yaml.safe_dump(d,sort_keys=False,allow_unicode=True,width=100))
s=(R/'RESOLVED.md').read_text();marker='**RA-08 (Solved).**';a=s.index(marker);b=s.index('\n\n',a);block=s[a:b].replace(marker,'**RA-08 (Lean verified; formalization by George Stepaniants).**',1)
block+=r''' **Lean verification — 2026-09-13:** George Stepaniants, Department of Computing and Mathematical Sciences, California Institute of Technology, Pasadena, California, USA, with AI-agent assistance. Matthew J. Colbrook retains mathematical authorship. The [fourteen exports](randomized-and-low-rank-approximation/RA-08/lean/Solution.lean) refute the complete original concave spectral-transfer implication, with genuine Euclidean operator norm/CFC and every selected eigenbasis retained. The unchanged witness has exact input and optimal tail error $t$ but strictly larger transformed error. The source's larger contour ratio, separate Nyström sketch identity and ancillary nuclear extensions are outside these exports. Exact algebra and a materially used explicit-kernel LeanCert singleton sign certificate suffice. Two independent statement and two independent final mathematical reviews were followed by [Ubuntu run 34735273999](https://github.com/sgstepaniants/OpenProblemsInNLA/actions/runs/34735273999), with all fourteen exports, default-kernel replay,59 standard-three reports and both real control suites passing. The [canonical evidence](randomized-and-low-rank-approximation/RA-08/README.md#lean-proof-and-verification-evidence---2026-09-13) links the independent operational audit and root acceptance binding all613 inputs. External human peer review is not claimed.'''
block=block.replace('replay,59','replay, 59').replace('all613','all 613');(R/'RESOLVED.md').write_text(s[:a]+block+s[b:])
(O/'prepare.py').write_bytes(Path(__file__).read_bytes());(O/'artifact-marker.json').write_text(json.dumps({'command':['node','/Users/georgestepaniants/.codex/plugins/cache/openai-primary-runtime/pdf/26.904.11930/skills/pdf/container_tools/mark_artifact_operation_started.mjs','--operation-kind','edit','--expected-output-count','1','--output-format','pdf'],'exit_code':0,'scope':'Ran successfully once immediately before initial publication authoring command.'},indent=2)+'\n')
print(json.dumps({'prepared':'RA-08','candidate_inputs':613,'immutable_operational_files':800,'target_unchanged':True},indent=2))
